---
title: "Length_Survival_analysis.Rmd"
author: "Sam Gurr"
date: "7/23/2021"
output:
  pdf_document: default
  html_document: default
---




# load libraries

```{r, include=FALSE}
library(ggplot2)
library(dplyr)
library(tidyverse)
library(multcompView)
library(agricolae)
library(dplyr)
library(lme4)
library(ggplot2)
library(nlme)
library(car)
library(performance)
library(stargazer)
library(emmeans)
library(pander)
library(survminer)
library(survival)
library(adjustedCurves)
library(riskRegression)
library(pammtools)
library(bestNormalize)
```


# Set Path & load data

```{r setup}

setwd("C:/Users/samjg/Documents/Github_repositories/Cvirginica_multistressor/RAnalysis")

# day 1 - length data
raw_length_dat_Age1    <- read.csv("Data/Length_Survival/timepoint_1_Day1.csv", header = T,nrows=50) %>% dplyr::mutate(Age = 1)


# day 1 - length data
raw_length_dat_Age4    <- read.csv("Data/Length_Survival/timepoint_2_Day4.csv", header = T) %>% dplyr::mutate(Age = 4)

# day 8 - length data
raw_length_dat_Age8_1  <- read.csv("Data/Length_Survival/timepoint_3_Day8.csv", header = T) %>% dplyr::mutate(Age = 8)
raw_length_dat_Age8_2  <- read.csv("Data/Length_Survival/timepoint_3_Day8_additional_lengths.csv", header = T) %>% dplyr::mutate(Age = 8)
rbind(raw_length_dat_Age8_1,raw_length_dat_Age8_2)


# day 11 - length data
raw_length_dat_Age11   <- read.csv("Data/Length_Survival/timepoint_4_Day11.csv", header = T) %>% 
                                    dplyr::mutate(Age = 11)

# day 15 - length data
raw_length_dat_Age15   <- read.csv("Data/Length_Survival/timepoint_5_Day15.csv", header = T) %>% 
                                    dplyr::select(-X) %>% 
                                    dplyr::mutate(Age = 15)

# master raw length file

Masterlengthdata    <- rbind(sapply(raw_length_dat_Age1, as.numeric),
                                sapply(raw_length_dat_Age4, as.numeric),
                                sapply(raw_length_dat_Age8_1, as.numeric), 
                                sapply(raw_length_dat_Age8_2, as.numeric),
                                sapply(raw_length_dat_Age11, as.numeric),
                                sapply(raw_length_dat_Age15, as.numeric))


# average data - survival and length
Av_length.survival_dat <- read.csv("Data/Length_Survival/LengthSurvival_master.csv", header = T) %>% 
                            dplyr::mutate(random_fact = paste( substr(Temp,1,1), 
                                                               substr(OA,1,1), 
                                                               substr(Salinity,1,1), '_', Replicate, sep = ''))
head(Av_length.survival_dat)
```


# prep data 

```{r, prep the raw data for stats} 
# extract the experiment data with corresponding sample Ids from the averaged data master file...
Exp_data <-  Av_length.survival_dat %>% 
                filter(Day %in% 1) %>% 
                dplyr::select(c('Temp','OA','Salinity','Replicate','Id.', 'pH', 'AR')) %>% 
                dplyr::rename(Sample.ID = Id., Aragonite_saturation = AR)

# melt the raw data, cean and format it for merging with Exp_data




# Age 1
raw_length_Age1MELT <-  reshape2::melt((as.data.frame(Masterlengthdata) %>% dplyr::filter(Age == 1))) %>% 
                        na.omit %>% 
                        dplyr::rename(length_um = value , Sample.ID =variable) %>% 
                        dplyr::mutate(Sample.ID = gsub('.*Sample.','', Sample.ID))

Age1_raw_length      <- merge(raw_length_Age1MELT, Exp_data, by = 'Sample.ID')  %>% 
                        dplyr::mutate(random_fact = paste( substr(Temp,1,1), substr(OA,1,1), substr(Salinity,1,1), '_', Replicate, sep = '')) %>%
                        dplyr::mutate(Age = 1)


# Age 4
raw_length_Age4MELT <-  reshape2::melt((as.data.frame(Masterlengthdata) %>% dplyr::filter(Age == 4))) %>% 
                        na.omit %>% 
                        dplyr::rename(length_um = value , Sample.ID =variable) %>% 
                        dplyr::mutate(Sample.ID = gsub('.*Sample.','', Sample.ID))

Age4_raw_length      <- merge(raw_length_Age4MELT, Exp_data, by = 'Sample.ID')  %>% 
                        dplyr::mutate(random_fact = paste( substr(Temp,1,1), substr(OA,1,1), substr(Salinity,1,1), '_', Replicate, sep = '')) %>%
                        dplyr::mutate(Age = 4)


# Age 8
raw_length_Age8MELT <-  reshape2::melt((as.data.frame(Masterlengthdata) %>% dplyr::filter(Age == 8))) %>% 
                        na.omit %>% 
                        dplyr::rename(length_um = value , Sample.ID =variable) %>% 
                        dplyr::mutate(Sample.ID = gsub('.*Sample.','', Sample.ID))

Age8_raw_length      <- merge(raw_length_Age8MELT, Exp_data, by = 'Sample.ID')  %>% 
                        dplyr::mutate(random_fact = paste( substr(Temp,1,1), substr(OA,1,1), substr(Salinity,1,1), '_', Replicate, sep = '')) %>%
                        dplyr::mutate(Age = 8)

# Age 11
raw_length_Age11MELT <-  reshape2::melt((as.data.frame(Masterlengthdata) %>% dplyr::filter(Age == 11))) %>% 
                        na.omit %>% 
                        dplyr::rename(length_um = value , Sample.ID =variable) %>% 
                        dplyr::mutate(Sample.ID = gsub('.*Sample.','', Sample.ID))

Age11_raw_length      <- merge(raw_length_Age11MELT, Exp_data, by = 'Sample.ID')  %>% 
                        dplyr::mutate(random_fact = paste( substr(Temp,1,1), substr(OA,1,1), substr(Salinity,1,1), '_', Replicate, sep = '')) %>%
                        dplyr::mutate(Age = 11)

# Age 15
raw_length_Age15MELT <- reshape2::melt((as.data.frame(Masterlengthdata) %>% dplyr::filter(Age == 15))) %>% 
                        na.omit %>% 
                        dplyr::rename(length_um = value , Sample.ID =variable) %>% 
                        dplyr::mutate(Sample.ID = gsub('.*Sample.','', Sample.ID))

Age15_raw_length      <- merge(raw_length_Age15MELT, Exp_data, by = 'Sample.ID')  %>% 
                        dplyr::mutate(random_fact = paste( substr(Temp,1,1), substr(OA,1,1), substr(Salinity,1,1), '_', Replicate, sep = '')) %>%
                        dplyr::mutate(Age = 15)

Master_Lengths <- rbind(Age1_raw_length,
                        Age4_raw_length,
                        Age8_raw_length,
                        Age11_raw_length,
                        Age15_raw_length)


```
 
 
 
 Plot all data
 
 
```{r,plot all length}

Length_means <- Master_Lengths %>% 
                          na.omit() %>% 
                          dplyr::group_by(Age, OA, Salinity, Temp) %>% 
                          dplyr::summarise(mean_length = mean(length_um), 
                                           n           = n(),
                                           sd_length   = sd(length_um),
                                           se_length   = sd_length/(sqrt(n))) 


GR_means <- as.data.frame(Length_means %>% 
  filter(Age %in% c(1,15)) %>% 
  dplyr::select(c(Age, OA, Salinity, Temp, mean_length)) %>% 
  dplyr::group_by(OA, Salinity, Temp)  %>% 
  tidyr::spread(Age, mean_length) %>%  # new columns titled 1 and 15 for he Age and with values for the 
  # length data grouped by treatment 
  dplyr::mutate(Growth_rate_umday = (`15` - `1`) / 14) %>% 
  dplyr::select(!c(`1`,`15`))) # note 1 missing value for OA High Temp Low Salinity Low

getNA <- as.data.frame(Length_means %>% 
  filter(Age %in% c(1,11)) %>% 
  dplyr::select(c(Age, OA, Salinity, Temp, mean_length)) %>% 
  dplyr::group_by(OA, Salinity, Temp)  %>% 
  tidyr::spread(Age, mean_length) %>%  # new columns titled 1 and 15 for he Age and with values for the 
  # length data grouped by treatment 
  dplyr::mutate(Growth_rate_umday = (`11` - `1`) / 13) %>% 
  dplyr::select(!c(`1`,`11`))) # 2.612424 for OA High Temp Low Salinity Low, insert into the other table

GR_means[4,4] = 2.612424

GR_means$Growth_rate_umday <- as.numeric(GR_means$Growth_rate_umday)

Length_means_MASTER <- merge(Length_means, GR_means, by=c('OA', 'Salinity', 'Temp'))

# plot - length
data <- Length_means_MASTER %>% 
                      dplyr::mutate(OA_Sal = paste(substr(OA,1,1),
                                              substr(Salinity,1,1),
                                                  sep = ''))
p <- data %>% 
       ggplot(aes(x = Age,
                  y = mean_length)) + 
       geom_point(color = 'grey80') +
       geom_line(aes(x = Age,
                     y = mean_length)) +
       geom_errorbar(aes(ymin = mean_length - se_length, 
                         ymax = mean_length + se_length), 
                         width = 0.5, position= "dodge2") +
       geom_smooth(method = "lm", se = FALSE, size = 0.5, color = 'white') +
       theme_bw() +  
       facet_grid(vars(Temp), vars(fct_relevel(OA_Sal, c("HL", "LL", "HH", "LH"))))
p <- p + geom_rect(data = data, aes(fill = Growth_rate_umday), xmin = -Inf, xmax = Inf, ymin = -Inf, ymax = Inf, alpha = 0.3)
p <- p + geom_text(data = data, size = 2, aes(x = 5, y = 300, label = paste0(round(Growth_rate_umday,2),"um day-1")))
p <- p + scale_fill_gradient(low = "orange", high = "forestgreen", aesthetics = "fill")
p
setwd("C:/Users/samjg/Documents/Github_repositories/Cvirginica_multistressor/RAnalysis")
pdf("Output/Length_Survival/Length_all_facetted.pdf", width=11, height=6)
print(p)
dev.off()

```

```{r}


Length_all_MeanSE_plot <- Length_means %>% 
                                ggplot(aes(x = Age,
                                           y=mean_length, 
                                           colour=fct_relevel(Salinity, c("Low", "High")), 
                                           linetype = Temp)) +
                                geom_point(aes(fill = fct_relevel(Salinity, c("Low", "High")), 
                                           shape = fct_relevel(OA, c("Low", "High"))),
                                           position = "dodge2") +
                                geom_line(aes(x = Age,
                                           y=mean_length, 
                                           colour=fct_relevel(Salinity, c("Low", "High")), 
                                           linetype = Temp)) +
                                geom_errorbar(aes(ymin = mean_length - se_length, 
                                                  ymax = mean_length + se_length), 
                                              width = 0.5, position= "dodge2") +
                                theme_classic() +  
                                facet_wrap(~(fct_relevel(OA, c("Low", "High"))))
setwd("C:/Users/samjg/Documents/Github_repositories/Cvirginica_multistressor/RAnalysis")
pdf("Output/Length_Survival/Length_all_MeanSE.pdf", width=11, height=6)
print(Length_all_MeanSE_plot)
dev.off()


# length data for scallops days 1 and 4 
Length_Day1.4_MeanSE_plot <- Length_means %>% 
                                dplyr::filter(Age %in% c(1, 4)) %>% 
                                ggplot(aes(x = Age,
                                           y=mean_length, 
                                           colour=fct_relevel(Salinity, c("Low", "High")), 
                                           linetype = Temp)) +
                                geom_point(aes(fill = fct_relevel(Salinity, c("Low", "High")), 
                                           shape = fct_relevel(OA, c("Low", "High"))),
                                           position = "dodge2") +
                                geom_line(aes(x = Age,
                                           y=mean_length, 
                                           colour=fct_relevel(Salinity, c("Low", "High")), 
                                           linetype = Temp)) +
                                geom_errorbar(aes(ymin = mean_length - se_length, 
                                                  ymax = mean_length + se_length), 
                                              width = 0.5, position= "dodge2") +
                                theme_classic() +  
                                facet_wrap(~(fct_relevel(OA, c("Low", "High"))))
setwd("C:/Users/samjg/Documents/Github_repositories/Cvirginica_multistressor/RAnalysis")
pdf("Output/Length_Survival/Length_Day1.4_MeanSE.pdf", width=11, height=6)
print(Length_Day1.4_MeanSE_plot)
dev.off()



# length data for scallops days after day 4
Length_Days8.11.15_MeanSE_plot <- Length_means %>% 
                                dplyr::filter(Age > 4) %>% 
                                ggplot(aes(x = Age,
                                           y=mean_length, 
                                           colour=fct_relevel(Salinity, c("Low", "High")), 
                                           linetype = Temp)) +
                                geom_point(aes(fill = fct_relevel(Salinity, c("Low", "High")), 
                                           shape = fct_relevel(OA, c("Low", "High"))),
                                           position = "dodge2") +
                                geom_line(aes(x = Age,
                                           y=mean_length, 
                                           colour=fct_relevel(Salinity, c("Low", "High")), 
                                           linetype = Temp)) +
                                geom_errorbar(aes(ymin = mean_length - se_length, 
                                                  ymax = mean_length + se_length), 
                                              width = 0.5, position= "dodge2") +
                                theme_classic() +  
                                facet_wrap(~(fct_relevel(OA, c("Low", "High"))))
setwd("C:/Users/samjg/Documents/Github_repositories/Cvirginica_multistressor/RAnalysis")
pdf("Output/Length_Survival/Length_Days8.11.15_MeanSE.pdf", width=11, height=6)
print(Length_Days8.11.15_MeanSE_plot)
dev.off()





# statistical approach test
Length_lme_mod<- lmer(length_um~OA*Temp*Salinity + (1+Age|random_fact),data=Master_Lengths)
pander(anova(Length_lme_mod), style='rmarkdown')
pvals.fnc(Length_lme_mod, nsims = n, withMCMC = TRUE)


ShellLength_Boxplot <- ggplot(data=Master_Lengths, aes(x=fct_relevel(OA, c("Low", "High")), 
                                                             y=length_um, 
                                                             colour=fct_relevel(Salinity, c("Low", "High")), 
                                                             linetype= Temp)) +
                              geom_boxplot() + 
                              theme_classic() +  
                              stat_summary(fun.y="mean",position = position_dodge2(width = 0.75)) +
                              theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank())+ 
                              theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))+
                              labs(title="Age = 24 hours", x ="pCO2 level", y = "Larvae size (μm)")+ 
                              theme(axis.title.y = element_text(size = rel(1.3), 
                                                                angle =90), 
                                    axis.title.x = element_text(size = rel(1.3), 
                                                                angle = 0))+
                              theme(axis.text=element_text(size=12)) +
                              facet_wrap(~Age)
ShellLength_Boxplot



ShellLength_Boxplot_Day1 <- Master_Lengths %>%  dplyr::filter(Age == 1) %>% 
                              ggplot(aes(x=fct_relevel(OA, c("Low", "High")), 
                                                             y=length_um, 
                                                             colour=fct_relevel(Salinity, c("Low", "High")), 
                                                             linetype= Temp)) +
                              geom_boxplot() + 
                              theme_classic() +  
                              stat_summary(fun.y="mean",position = position_dodge2(width = 0.75)) +
                              theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank())+ 
                              theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))+
                              labs(title="Age = 24 hours", x ="pCO2 level", y = "Larvae size (μm)")+ 
                              theme(axis.title.y = element_text(size = rel(1.3), 
                                                                angle =90), 
                                    axis.title.x = element_text(size = rel(1.3), 
                                                                angle = 0))+
                              theme(axis.text=element_text(size=12))
ShellLength_Boxplot_Day1


ShellLength_Boxplot_Days4.8 <- Master_Lengths %>%  dplyr::filter(Age %in% c(4, 8)) %>% 
                              ggplot(aes(x=fct_relevel(OA, c("Low", "High")), 
                                                             y=length_um, 
                                                             colour=fct_relevel(Salinity, c("Low", "High")), 
                                                             linetype= Temp)) +
                              geom_boxplot() + 
                              theme_classic() +  
                              stat_summary(fun.y="mean",position = position_dodge2(width = 0.75)) +
                              theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank())+ 
                              theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))+
                              labs(title="Age = 4 and 8 days", x ="pCO2 level", y = "Larvae size (μm)")+ 
                              theme(axis.title.y = element_text(size = rel(1.3), 
                                                                angle =90), 
                                    axis.title.x = element_text(size = rel(1.3), 
                                                                angle = 0))+
                              theme(axis.text=element_text(size=12)) +
                              facet_wrap(~Age)
ShellLength_Boxplot_Days4.8


ShellLength_Boxplot_Days11.15 <-  Master_Lengths %>%  dplyr::filter(Age %in% c(11, 15)) %>% 
                              ggplot(aes(x=fct_relevel(OA, c("Low", "High")), 
                                                             y=length_um, 
                                                             colour=fct_relevel(Salinity, c("Low", "High")), 
                                                             linetype= Temp)) +
                              geom_boxplot() + 
                              theme_classic() +  
                              stat_summary(fun.y="mean",position = position_dodge2(width = 0.75)) +
                              theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank())+ 
                              theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))+
                              labs(title="Age = 11 and 15 days", x ="pCO2 level", y = "Larvae size (μm)")+ 
                              theme(axis.title.y = element_text(size = rel(1.3), 
                                                                angle =90), 
                                    axis.title.x = element_text(size = rel(1.3), 
                                                                angle = 0))+
                              theme(axis.text=element_text(size=12)) +
                              facet_wrap(~OA*Age)
ShellLength_Boxplot_Days11.15
```




```{r survival plot all} 
p<-ggplot(data=data, aes(x=interval, y=OR, colour=Drug)) + geom_point() + geom_line()
p<-p+geom_ribbon(aes(ymin=data$lower, ymax=data$upper), linetype=2, alpha=0.1)


Survival_means_day1         <- Av_length.survival_dat %>% 
                                dplyr::filter(Day == 1) %>% 
                                na.omit() %>% 
                                dplyr::group_by(Day, OA, Salinity, Temp) %>% 
                                dplyr::summarise(mean_survival = mean(Survival), 
                                                 n           = n(),
                                                 sd_survival   = sd(Survival),
                                                 se_survival   = sd_survival/(sqrt(n)))


Survival_all_MeanSE_plot_Day1 <- Survival_means_day1 %>% 
                                  dplyr::mutate(AllTreat = as.factor(paste(OA, Salinity, Temp, sep = '_'))) %>% 
                                  ggplot(aes(x = as.numeric(Day),
                                             y = mean_survival, 
                                             group = AllTreat,
                                             colour=fct_relevel(Salinity, c("Low", "High")), 
                                             linetype = Temp)) +
                                  geom_point(aes(colour = fct_relevel(Salinity, c("Low", "High")), 
                                             shape = fct_relevel(OA, c("Low", "High"))),
                                             width = 0.5,
                                             position = "dodge2") +
                                  geom_line(aes(x = as.numeric(Day),
                                             y=mean_survival, 
                                             colour=fct_relevel(Salinity, c("Low", "High")), 
                                             linetype = Temp)) +
                                  geom_errorbar(aes(ymin = mean_survival - se_survival, 
                                                    ymax = mean_survival + se_survival), 
                                                width = 0.5, position= "dodge2") +
                                  theme_classic() +  
                                  facet_wrap(~(fct_relevel(OA, c("Low", "High"))))



# plot - Survival  after day 1!!!

Survival_means <- Av_length.survival_dat %>% 
                          dplyr::filter(Day >1) %>% 
                          na.omit() %>% 
                          dplyr::group_by(Day, OA, Salinity, Temp) %>% 
                          dplyr::summarise(mean_survival = mean(Survival), 
                                           n           = n(),
                                           sd_survival   = sd(Survival),
                                           se_survival   = sd_survival/(sqrt(n)))



Mortality_rate_means <- as.data.frame(Survival_means %>% 
  filter(Day %in% 15) %>% 
  dplyr::select(c(Day, OA, Salinity, Temp, mean_survival)) %>% 
  dplyr::group_by(OA, Salinity, Temp)  %>% 
  tidyr::spread(Day, mean_survival) %>%  # new columns titled 1 and 15 for he Age and with values for the 
  # length data grouped by treatment 
  dplyr::mutate(Mortality_rate_percday = (`15`) *100 ) %>% 
  dplyr::select(!`15`)) 

Survival_means_MASTER <- merge(Survival_means, Mortality_rate_means, by=c('OA', 'Salinity', 'Temp'))

# plot - length
data <- Survival_means_MASTER %>% 
                      dplyr::mutate(OA_Sal = paste(substr(OA,1,1),
                                              substr(Salinity,1,1),
                                                  sep = ''))
p <- data %>% 
       ggplot(aes(x = Day,
                  y = mean_survival)) + 
       geom_point(color = 'grey80') +
       geom_line(aes(x = Day,
                     y = mean_survival)) +
       geom_errorbar(aes(ymin = mean_survival - se_survival, 
                         ymax = mean_survival + se_survival), 
                         width = 0.5, position= "dodge2") +
       geom_smooth(method = "lm", se = FALSE, size = 0.5, color = 'white') +
       theme_bw() +  
       facet_grid(vars(Temp), vars(fct_relevel(OA_Sal, c("HL", "LL", "HH", "LH"))))
p <- p + geom_rect(data = data, aes(fill = Mortality_rate_percday), 
                   xmin = -Inf, 
                   xmax = Inf, 
                   ymin = -Inf, 
                   ymax = Inf, 
                   alpha = 0.3)
p <- p + geom_text(data = data, size = 2, 
                   aes(x = 12, 
                       y = 0.8, 
                       label = paste0(round(Mortality_rate_percday,2),"% day-1")))
p <-p + scale_fill_gradient(low = "forestgreen", high = "orange", aesthetics = "fill")
setwd("C:/Users/samjg/Documents/Github_repositories/Cvirginica_multistressor/RAnalysis")
pdf("Output/Length_Survival/Survival_all_facetted.pdf", width=11, height=6)
print(p)
dev.off()


Survival_all_MeanSE_plot <- Survival_means %>% 
                                dplyr::mutate(AllTreat = as.factor(paste(OA, Salinity, Temp, sep = '_'))) %>% 
                                ggplot(aes(x = as.numeric(Day),
                                           y = mean_survival, 
                                           group = AllTreat,
                                           colour=fct_relevel(Salinity, c("Low", "High")), 
                                           linetype = Temp)) +
                                geom_point(aes(colour = fct_relevel(Salinity, c("Low", "High")), 
                                           shape = fct_relevel(OA, c("Low", "High"))),
                                           width = 0.5,
                                           position = "dodge2") +
                                geom_line(aes(x = as.numeric(Day),
                                           y=mean_survival, 
                                           colour=fct_relevel(Salinity, c("Low", "High")), 
                                           linetype = Temp)) +
                                geom_errorbar(aes(ymin = mean_survival - se_survival, 
                                                  ymax = mean_survival + se_survival), 
                                              width = 0.5, position= "dodge2") +
                                theme_classic() +  
                                stat_summary(geom="ribbon", fun.data=mean_cl_normal, width=0.1, conf.int=0.95, fill="lightblue")+
                                facet_wrap(~(fct_relevel(OA, c("Low", "High"))))
Survival_all_MeanSE_plot # view the plot
setwd("C:/Users/samjg/Documents/Github_repositories/Cvirginica_multistressor/RAnalysis")
pdf("Output/Length_Survival/Survival_all_MeanSE.pdf", width=11, height=6)
print(Survival_all_MeanSE_plot)
dev.off()
```
 
 
:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
# Length ::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::  :::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::


### Age 24 hours ALL DATA ------------

```{r, LENGTH Age 24 hours size - all data}

# Age 1 Length mod - all data -------------------------------------------------------------------------------------- #


Age1Length_lme_mod <- lme(length_um~OA*Temp*Salinity,random=~1|random_fact,data=Age1_raw_length)
pander(anova(Age1Length_lme_mod), style='rmarkdown') # anova table of lmer
# |        &nbsp;        | numDF | denDF | F-value |  p-value  |
# |:--------------------:|:-----:|:-----:|:-------:|:---------:|
# |   **(Intercept)**    |   1   | 1176  | 151157  |     0     |
# |        **OA**        |   1   |  16   |  108.4  | 1.56e-08  | *
# |       **Temp**       |   1   |  16   |  18.6   | 0.0005359 | *
# |     **Salinity**     |   1   |  16   |  120.4  | 7.426e-09 | *
# |     **OA:Temp**      |   1   |  16   |  1.363  |  0.2601   |
# |   **OA:Salinity**    |   1   |  16   |  5.876  |  0.02756  | *
# |  **Temp:Salinity**   |   1   |  16   |  2.105  |  0.1661   |
# | **OA:Temp:Salinity** |   1   |  16   |  1.135  |  0.3026   |
leveneTest(residuals(Age1Length_lme_mod) ~ Age1_raw_length$Temp*Age1_raw_length$OA*Age1_raw_length$Salinity) # 0.2716 PASS
boxplot(residuals(Age1Length_lme_mod) ~ Age1_raw_length$Temp*Age1_raw_length$OA*Age1_raw_length$Salinity) # visual of residuals grouped
qqnorm(resid(Age1Length_lme_mod)) # check for normality of residuals       
# post hoc tests --------------------------------------------------------------------------------------------------- #
posthoc<-emmeans(Age1Length_lme_mod, pairwise~OA:Salinity, adjust="tukey")
multcomp::cld(posthoc$emmeans,alpha = 0.5, Letters = letters)
 # OA   Salinity emmean    SE df lower.CL upper.CL .group
 # High Low        67.7 0.371 16     66.9     68.5  a    
 # Low  Low        72.5 0.371 16     71.7     73.3   b   
 # High High       72.7 0.371 16     71.9     73.5   b   
 # Low  High       75.6 0.371 16     74.9     76.4    c 

# run model (lm mod)
Age1Length_lm_mod <- lm(length_um~OA*Temp*Salinity,data=Age1_raw_length)
pander(anova(Age1Length_lm_mod), style='rmarkdown') # anova table of lmer
# |        &nbsp;        |  Df  | Sum Sq | Mean Sq | F value |  Pr(>F)   |
# |:--------------------:|:----:|:------:|:-------:|:-------:|:---------:|
# |        **OA**        |  1   |  4478  |  4478   |  419.8  | 3.562e-80 | *
# |       **Temp**       |  1   | 768.3  |  768.3  |  72.03  | 6.209e-17 | *
# |     **Salinity**     |  1   |  4974  |  4974   |  466.3  | 1.503e-87 | *
# |     **OA:Temp**      |  1   |  56.3  |  56.3   |  5.278  |  0.02177  | *
# |   **OA:Salinity**    |  1   | 242.7  |  242.7  |  22.75  | 2.069e-06 | *
# |  **Temp:Salinity**   |  1   | 86.96  |  86.96  |  8.153  | 0.004374  | *
# | **OA:Temp:Salinity** |  1   | 46.86  |  46.86  |  4.393  |  0.03629  | *
# |    **Residuals**     | 1192 | 12714  |  10.67  |   NA    |    NA     |
shapiro.test(residuals(Age1Length_lm_mod)) # 0.002907 no pass
leveneTest(residuals(Age1Length_lm_mod) ~ Age1_raw_length$Temp*Age1_raw_length$OA*Age1_raw_length$Salinity) # 0.2793 PASS
boxplot(residuals(Age1Length_lm_mod) ~ Age1_raw_length$Temp*Age1_raw_length$OA*Age1_raw_length$Salinity) # visual of residuals grouped
qqnorm(resid(Age1Length_lm_mod)) # check for normality of residuals       
ggplot(Age1_raw_length, aes(x = length_um)) + geom_histogram(binwidth = 1, fill = "white", colour = "black") # histogram



# post hoc tests --------------------------------------------------------------------------------------------------- #
posthoc<-emmeans(Age1Length_lm_mod, pairwise~OA:Salinity:Temp, adjust="tukey")
multcomp::cld(posthoc$emmeans,alpha = 0.5, Letters = letters)
 # OA   Salinity Temp emmean    SE   df lower.CL upper.CL .group 
 # High Low      Low    66.8 0.267 1192     66.2     67.3  a      
 # High Low      High   68.7 0.267 1192     68.1     69.2   b     
 # High High     Low    71.6 0.267 1192     71.1     72.1    c    
 # Low  Low      Low    72.4 0.267 1192     71.8     72.9     d   
 # Low  Low      High   72.6 0.267 1192     72.1     73.1     d   
 # High High     High   73.8 0.267 1192     73.2     74.3      e  
 # Low  High     Low    74.6 0.267 1192     74.1     75.1       f 
 # Low  High     High   76.7 0.267 1192     76.2     77.2        g


# plot the data  ----------------------------------------------------------------------------------------------------- #


Age1_ShellLength_Boxplot <- ggplot(data=Age1_raw_length, aes(x=fct_relevel(OA, c("Low", "High")), 
                                                             y=length_um, 
                                                             colour=fct_relevel(Salinity, c("Low", "High")), 
                                                             linetype= Temp)) +
                              geom_boxplot() + 
                              theme_classic() +  
                              stat_summary(fun.y="mean",position = position_dodge2(width = 0.75)) +
                              theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank())+ 
                              theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))+
                              labs(title="Age = 24 hours", x ="pCO2 level", y = "Larvae size (μm)")+ 
                              theme(axis.title.y = element_text(size = rel(1.3), angle =90), axis.title.x = element_text(size = rel(1.3), angle = 0))+
                              theme(axis.text=element_text(size=12)) 

# save the plot 
setwd("C:/Users/samjg/Documents/Github_repositories/Cvirginica_multistressor/RAnalysis")
pdf("Output/Length_Survival/Length_age_24hrs_Boxplots.pdf", width=8, height=6)
print(Age1_ShellLength_Boxplot)
dev.off()




# -------------------------------------------------------------------------------------------------------------------- #


# For the results section -  expand upon the mean sd and percent differences in the Tukey HSD 
Age1_Length_Table <- Age1_raw_length %>% 
                        dplyr::group_by(OA,Salinity) %>% 
                        dplyr::summarise(mean_length = mean(length_um),
                                         n = n(),
                                         sd_length = sd(length_um),
                                         se_length = sd_length/(sqrt(n)))

# how many animals were measured per replicate / per treatment?
Age1_raw_length %>% 
            dplyr::group_by(random_fact) %>% 
            dplyr::summarise(n = n())
```


### Age 24 hours HIGH TEMP ONLY ------------


```{r, LENGTH Age 24 hours - HIGH TEMP ONLY}
### Age 24 hours HIGH TEMP ONLY  ------------
# -------------------------------------------------------------------------------------------------------------------- #
# High temp only 

#data 
Age1_raw_length_hightemp <- Age1_raw_length %>% dplyr::filter(!Temp %in% 'Low')

# run model (LME)
Age1Length_lme_mod_hightemp <- lme(length_um~OA*Salinity,random=~1|random_fact,data=Age1_raw_length_hightemp) # notice temp is removed...
pander(anova(Age1Length_lme_mod_hightemp), style='rmarkdown') # anova table of lmer

# |     &nbsp;      | numDF | denDF | F-value |  p-value  |
# |:---------------:|:-----:|:-----:|:-------:|:---------:|
# | **(Intercept)** |   1   |  588  | 105297  |     0     |
# |     **OA**      |   1   |   8   |  58.24  | 6.121e-05 |
# |  **Salinity**   |   1   |   8   |  105.2  | 7.024e-06 |
# | **OA:Salinity** |   1   |   8   |  1.258  |  0.2945   |
leveneTest(residuals(Age1Length_lme_mod_hightemp) ~Age1_raw_length_hightemp$OA*Age1_raw_length_hightemp$Salinity) # 0.4058 PASS
Levenboxplot(residuals(Age1Length_lme_mod_hightemp) ~ Age1_raw_length_hightemp$OA*Age1_raw_length_hightemp$Salinity) # visual of residuals grouped
qqnorm(resid(Age1Length_lme_mod_hightemp)) # check for normality of residuals       


# run model (LM)
Age1Length_lm_mod_hightemp <- lm(length_um~OA*Salinity,data=Age1_raw_length_hightemp) # notice temp is removed...
pander(anova(Age1Length_lm_mod_hightemp), style='rmarkdown') # anova table of lmer
# |     &nbsp;      | Df  | Sum Sq | Mean Sq | F value |  Pr(>F)   |
# |:---------------:|:---:|:------:|:-------:|:-------:|:---------:|
# |     **OA**      |  1  |  1765  |  1765   |  155.6  | 6.78e-32  |
# |  **Salinity**   |  1  |  3188  |  3188   |  281.1  | 5.767e-52 |
# | **OA:Salinity** |  1  | 38.13  |  38.13  |  3.362  |  0.06722  |
# |  **Residuals**  | 596 |  6760  |  11.34  |   NA    |    NA     |
shapiro.test(residuals(Age1Length_lm_mod_hightemp)) # 0.2515 pass
leveneTest(residuals(Age1Length_lm_mod_hightemp) ~Age1_raw_length_hightemp$OA*Age1_raw_length_hightemp$Salinity) # 0.444 PASS
Levenboxplot(residuals(Age1Length_lm_mod_hightemp) ~ Age1_raw_length_hightemp$OA*Age1_raw_length_hightemp$Salinity) # visual of residuals grouped
qqnorm(resid(Age1Length_lm_mod_hightemp)) # check for normality of residuals       



# high temp only
Age1_ShellLength_Boxplot_hightemp <- ggplot(data=Age1_raw_length_hightemp, aes(x=fct_relevel(OA, c("Low", "High")), 
                                                                     y=length_um, 
                                                                     colour=fct_relevel(Salinity, c("Low", "High")))) +
                                      geom_boxplot() + 
                                      theme_classic() +  
                                      stat_summary(fun.y="mean",position = position_dodge2(width = 0.75)) +
                                      theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank())+ 
                                      theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))+
                                      labs(title="Age = 24 hours (high temp only)", x ="pCO2 level", y = "Larvae size (μm)")+ 
                                      theme(axis.title.y = element_text(size = rel(1.3), angle =90), axis.title.x = element_text(size = rel(1.3), angle = 0))+
                                      theme(axis.text=element_text(size=12)) 

# save the plot 
setwd("C:/Users/samjg/Documents/Github_repositories/Cvirginica_multistressor/RAnalysis")
pdf("Output/Length_Survival/Length_age_24hrs_Boxplots_hightemp.pdf", width=8, height=6)
print(Age1_ShellLength_Boxplot_hightemp)
dev.off()

```


### Age 4 days ALL DATA  ------------

```{r, LENGTH Age 4 days hours size - all data}


# Age 4 Length mod - all data -------------------------------------------------------------------------------------- #


Age4Length_lme_mod <- lme(length_um~OA*Salinity*Temp,random=~1|random_fact,data=Age4_raw_length)
pander(anova(Age4Length_lme_mod), style='rmarkdown') # anova table of lmer
# |        &nbsp;        | numDF | denDF | F-value |  p-value  |
# |:--------------------:|:-----:|:-----:|:-------:|:---------:|
# |   **(Intercept)**    |   1   |  378  |  10702  |     0     |
# |        **OA**        |   1   |  16   |  30.04  | 5.033e-05 |
# |     **Salinity**     |   1   |  16   |  13.73  | 0.001921  |
# |       **Temp**       |   1   |  16   |  1.675  |   0.214   |
# |   **OA:Salinity**    |   1   |  16   | 0.6367  |  0.4366   |
# |     **OA:Temp**      |   1   |  16   |  10.42  | 0.005262  | *
# |  **Salinity:Temp**   |   1   |  16   | 0.3258  |   0.576   |
# | **OA:Salinity:Temp** |   1   |  16   |  2.811  |  0.1131   |
leveneTest(residuals(Age4Length_lme_mod) ~ Age4_raw_length$Temp*Age4_raw_length$OA*Age4_raw_length$Salinity) # 0.2059 pass
boxplot(residuals(Age4Length_lme_mod) ~ Age4_raw_length$Temp*Age4_raw_length$OA*Age4_raw_length$Salinity) # visual of residuals grouped
qqnorm(resid(Age4Length_lme_mod)) # check for normality of residuals - looks okay

posthoc<-emmeans(Age4Length_lme_mod, pairwise~OA:Temp, adjust="tukey")
multcomp::cld(posthoc$emmeans,alpha = 0.5, Letters = letters)
 # OA   Temp emmean   SE df lower.CL upper.CL .group
 # High High   74.7 1.62 16     71.2     78.1  a    
 # High Low    77.7 1.58 16     74.4     81.1  a    
 # Low  Low    81.8 1.50 16     78.6     84.9   b   
 # Low  High   88.7 1.57 16     85.3     92.0    c 

Age4Length_lm_mod <- lm(length_um~OA*Salinity*Temp,data=Age4_raw_length)
pander(anova(Age4Length_lm_mod), style='rmarkdown') # anova table of lmr
# |        &nbsp;        | Df  | Sum Sq | Mean Sq | F value |  Pr(>F)   |
# |:--------------------:|:---:|:------:|:-------:|:-------:|:---------:|
# |        **OA**        |  1  |  6415  |  6415   |  83.8   | 3.006e-18 |
# |     **Salinity**     |  1  |  2701  |  2701   |  35.28  | 6.28e-09  |
# |       **Temp**       |  1  |  469   |   469   |  6.126  |  0.01374  |
# |   **OA:Salinity**    |  1  | 202.2  |  202.2  |  2.641  |  0.1049   |
# |     **OA:Temp**      |  1  |  2582  |  2582   |  33.73  | 1.309e-08 |
# |  **Salinity:Temp**   |  1  | 20.36  |  20.36  | 0.2659  |  0.6064   |
# | **OA:Salinity:Temp** |  1  | 864.4  |  864.4  |  11.29  | 0.0008547 |
# |    **Residuals**     | 394 | 30163  |  76.56  |   NA    |    NA     |
shapiro.test(residuals(Age4Length_lm_mod)) # 0.1884
leveneTest(residuals(Age4Length_lm_mod) ~ Age4_raw_length$Temp*Age4_raw_length$OA*Age4_raw_length$Salinity) # 0.1496 pass
boxplot(residuals(Age4Length_lm_mod) ~ Age4_raw_length$Temp*Age4_raw_length$OA*Age4_raw_length$Salinity) # visual of residuals grouped
qqnorm(resid(Age4Length_lm_mod)) # check for normality of residuals - looks okay




# post hoc tests --------------------------------------------------------------------------------------------------- #
posthoc<-emmeans(Age4Length_lm_mod, pairwise~OA:Salinity:Temp, adjust="tukey")
multcomp::cld(posthoc$emmeans,alpha = 0.5, Letters = letters)
 # OA   Salinity Temp emmean   SE  df lower.CL upper.CL .group
 # High Low      Low    72.5 1.30 394     69.9     75.1  a    
 # High Low      High   73.2 1.57 394     70.1     76.2  a    
 # High High     High   76.1 1.28 394     73.6     78.6  a    
 # Low  Low      Low    80.9 1.07 394     78.8     83.0   b   
 # Low  High     Low    83.2 1.11 394     81.0     85.4   bc  
 # High High     Low    83.2 1.24 394     80.8     85.7   bc  
 # Low  Low      High   85.5 1.16 394     83.2     87.8    c  
 # Low  High     High   92.1 1.33 394     89.5     94.7     d 

# plot the data  ----------------------------------------------------------------------------------------------------- #


require(forcats)
Age4_ShellLength_Boxplot <- ggplot(data=Age4_raw_length, aes(x=fct_relevel(OA, c("Low", "High")), 
                                                             y=length_um, 
                                                             colour=fct_relevel(Salinity, c("Low", "High")), 
                                                             linetype= Temp)) +
                              geom_boxplot() + 
                              theme_bw() +  
                              stat_summary(fun.y="mean",position = position_dodge2(width = 0.75)) +
                              theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank())+ 
                              theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))+
                              labs(title="Age = 4 days", x ="pCO2 level", y = "Shell Length (μm)")+ 
                              theme(axis.title.y = element_text(size = rel(1.3), angle =90), axis.title.x = element_text(size = rel(1.3), angle = 0))+
                              theme(axis.text=element_text(size=12)) 

setwd("C:/Users/samjg/Documents/Github_repositories/Cvirginica_multistressor/RAnalysis")
pdf("Output/Length_Survival/Length_age_4days_Boxplots.pdf", width=4, height=6)
print(Age4_ShellLength_Boxplot)
dev.off()

```


### Age 8 days ALL DATA  ------------

```{r, LENGTH Age 8 days hours size - all data}


# Age 8 Length mod - all data -------------------------------------------------------------------------------------- #


Age8Length_lme_mod <- lme(log(length_um)~OA*Salinity*Temp,random=~1|random_fact,data=Age8_raw_length)
pander(anova(Age8Length_lme_mod), style='rmarkdown') # anova table of lmer
# |        &nbsp;        | numDF | denDF | F-value |  p-value  |
# |:--------------------:|:-----:|:-----:|:-------:|:---------:|
# |   **(Intercept)**    |   1   | 1659  |  52761  |     0     |
# |        **OA**        |   1   |  16   |  17.24  | 0.0007493 |
# |     **Salinity**     |   1   |  16   |  17.66  | 0.000676  |
# |       **Temp**       |   1   |  16   |  3.026  |  0.1011   |
# |   **OA:Salinity**    |   1   |  16   | 0.08178 |  0.7786   |
# |     **OA:Temp**      |   1   |  16   |  4.522  |  0.04937  | **
# |  **Salinity:Temp**   |   1   |  16   |  3.228  |  0.09127  |
# | **OA:Salinity:Temp** |   1   |  16   |  1.939  |  0.1829   |
leveneTest(residuals(Age8Length_lme_mod) ~ Age8_raw_length$Temp*Age8_raw_length$OA*Age8_raw_length$Salinity) # < 2.2e-16 *** - did not pass
boxplot(residuals(Age8Length_lme_mod) ~ Age8_raw_length$Temp*Age8_raw_length$OA*Age8_raw_length$Salinity) # visual of residuals grouped
qqnorm(resid(Age8Length_lme_mod)) # check for normality of residuals - looks okay


# post hoc tests --------------------------------------------------------------------------------------------------- #
posthoc<-emmeans(Age8Length_lme_mod, pairwise~OA:Temp, adjust="tukey")
multcomp::cld(posthoc$emmeans,alpha = 0.5, Letters = letters)
 # OA   Temp emmean   SE df lower.CL upper.CL .group
 # High High   94.2 4.45 16     84.8      104  a    
 # High Low    95.4 4.38 16     86.1      105  ab   
 # Low  Low   104.0 4.36 16     94.8      113   b   
 # Low  High  123.5 4.34 16    114.3      133    c  


#  run model (lm)
Age8Length_lm_mod <- lm(length_um~OA*Salinity*Temp,data=Age8_raw_length)
pander(anova(Age8Length_lm_mod), style='rmarkdown') # anova table of lmr
# |        &nbsp;        |  Df  | Sum Sq | Mean Sq | F value |  Pr(>F)   |
# |:--------------------:|:----:|:------:|:-------:|:-------:|:---------:|
# |        **OA**        |  1   | 87009  |  87009  |  269.5  | 3.636e-54 |
# |     **Salinity**     |  1   | 76531  |  76531  |  237.1  | 1.894e-48 |
# |       **Temp**       |  1   | 25675  |  25675  |  79.53  | 2.022e-18 |
# |   **OA:Salinity**    |  1   |  3917  |  3917   |  12.13  | 0.0005157 |
# |     **OA:Temp**      |  1   | 37837  |  37837  |  117.2  | 5.505e-26 |
# |  **Salinity:Temp**   |  1   | 27137  |  27137  |  84.06  | 2.408e-19 |
# | **OA:Salinity:Temp** |  1   | 21019  |  21019  |  65.11  | 1.898e-15 |
# |    **Residuals**     | 1065 | 343803 |  322.8  |   NA    |    NA     |
shapiro.test(residuals(Age8Length_lm_mod)) # 1.397e-14
leveneTest(residuals(Age8Length_lm_mod) ~ Age8_raw_length$Temp*Age8_raw_length$OA*Age8_raw_length$Salinity) # < 2.2e-16 *** - did not pass
boxplot(residuals(Age8Length_lm_mod) ~ Age8_raw_length$Temp*Age8_raw_length$OA*Age8_raw_length$Salinity) # visual of residuals grouped
qqnorm(resid(Age8Length_lm_mod)) # check for normality of residuals - looks okay




# post hoc tests --------------------------------------------------------------------------------------------------- #
posthoc<-emmeans(Age8Length_lm_mod, pairwise~OA:Salinity:Temp, adjust="tukey")
multcomp::cld(posthoc$emmeans,alpha = 0.5, Letters = letters)
 # OA   Salinity Temp emmean   SE   df lower.CL upper.CL .group
 # High Low      High   87.4 1.83 1065     83.8     91.0  a    
 # High Low      Low    90.7 1.75 1065     87.3     94.1  a    
 # High High     High  101.1 1.47 1065     98.3    104.0   b   
 # Low  Low      Low   103.5 1.61 1065    100.3    106.6   bc  
 # High High     Low   103.5 1.47 1065    100.6    106.4   bc  
 # Low  Low      High  105.2 1.49 1065    102.2    108.1   bc  
 # Low  High     Low   105.5 1.47 1065    102.6    108.3    c  
 # Low  High     High  144.0 1.47 1065    141.1    146.8     d 

# plot the data  ----------------------------------------------------------------------------------------------------- #


require(forcats)
Age8_ShellLength_Boxplot <- ggplot(data=Age8_raw_length, aes(x=fct_relevel(OA, c("Low", "High")), 
                                                             y=length_um, 
                                                             colour=fct_relevel(Salinity, c("Low", "High")), 
                                                             linetype= Temp)) +
                              geom_boxplot() + 
                              theme_bw() +  
                              stat_summary(fun.y="mean",position = position_dodge2(width = 0.75)) +
                              theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank())+ 
                              theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))+
                              labs(title="Age = 8 days", x ="pCO2 level", y = "Shell Length (μm)")+ 
                              theme(axis.title.y = element_text(size = rel(1.3), angle =90),
                                    axis.title.x = element_text(size = rel(1.3), angle = 0))+
                              theme(axis.text=element_text(size=12)) 

setwd("C:/Users/samjg/Documents/Github_repositories/Cvirginica_multistressor/RAnalysis")
pdf("Output/Length_Survival/Length_age_8days_Boxplots.pdf", width=8, height=6)
print(Age8_ShellLength_Boxplot)
dev.off()

```


### Age 8 days HIGH TEMP ONLY ------------


```{r LENGTH Age 8 days hours size - HIGH TEMP ONLY}

# High temp only 

#data 
Age8_raw_length_hightemp <- Age8_raw_length %>% dplyr::filter(!Temp %in% 'Low')

# run model ( LME model)
Age8Length_lme_mod_hightemp <- lme(length_um~OA*Salinity,random=~1|random_fact,data=Age8_raw_length_hightemp) # notice temp is removed...
pander(anova(Age8Length_lme_mod_hightemp), style='rmarkdown') # anova table of lmer
# |     &nbsp;      | numDF | denDF | F-value | p-value  |
# |:---------------:|:-----:|:-----:|:-------:|:--------:|
# | **(Intercept)** |   1   |  531  |  1176   |    0     |
# |     **OA**      |   1   |   7   |  19.48  | 0.003104 | *
# |  **Salinity**   |   1   |   7   |  17.82  | 0.00393  | *
# | **OA:Salinity** |   1   |   7   |  3.686  | 0.09635  | (marginal)
leveneTest(residuals(Age8Length_lme_mod_hightemp) ~Age8_raw_length_hightemp$OA*Age8_raw_length_hightemp$Salinity) # 6.08e-12 *** no pass
boxplot(residuals(Age8Length_lme_mod_hightemp) ~ Age8_raw_length_hightemp$OA*Age8_raw_length_hightemp$Salinity) # visual of residuals grouped
qqnorm(resid(Age8Length_lme_mod_hightemp)) # check for normality of residuals       




# run lm model
Age8Length_lm_mod_hightemp <- lm((length_um)~OA*Salinity,data=Age8_raw_length_hightemp) # notice temp is removed...
pander(anova(Age8Length_lm_mod_hightemp), style='rmarkdown') # anova table of lmer
# |     &nbsp;      | Df  | Sum Sq | Mean Sq | F value |  Pr(>F)   |
# |:---------------:|:---:|:------:|:-------:|:-------:|:---------:|
# |     **OA**      |  1  | 113332 | 113332  |  277.2  | 1.649e-50 |
# |  **Salinity**   |  1  | 101921 | 101921  |  249.3  | 2.008e-46 |
# | **OA:Salinity** |  1  | 20519  |  20519  |  50.19  | 4.392e-12 |
# |  **Residuals**  | 538 | 219948 |  408.8  |   NA    |    NA     |
shapiro.test(residuals(Age8Length_lm_mod_hightemp)) #2.015e-11
leveneTest(residuals(Age8Length_lm_mod_hightemp) ~Age8_raw_length_hightemp$OA*Age8_raw_length_hightemp$Salinity) # 1.054e-08 *** no pass
boxplot(residuals(Age8Length_lme_mod_hightemp) ~ Age8_raw_length_hightemp$OA*Age8_raw_length_hightemp$Salinity) # visual of residuals grouped
qqnorm(resid(Age8Length_lme_mod_hightemp)) # check for normality of residuals       


# post hoc tests --------------------------------------------------------------------------------------------------- #

posthoc<-lsmeans(Age8Length_lme_mod_hightemp, ~OA*Salinity, adjust="tukey")
posthoc<-emmeans(Age8Length_lme_mod_hightemp, pairwise~OA*Salinity, adjust="tukey")

multcomp::cld(posthoc$emmeans,alpha = 0.5, Letters = letters)
 # OA   Salinity emmean   SE df lower.CL upper.CL .group
 # High Low        87.5 7.62  7     69.5      106  a    
 # High High      101.1 6.22 10     87.3      115  ab   
 # Low  Low       105.0 6.22  7     90.3      120   b   
 # Low  High      144.0 6.22  7    129.3      159    c  




# high temp only
Age8_ShellLength_Boxplot_hightemp <- ggplot(data=Age8_raw_length_hightemp, aes(x=fct_relevel(OA, c("Low", "High")), 
                                                                     y=length_um, 
                                                                     colour=fct_relevel(Salinity, c("Low", "High")))) +
                                      geom_boxplot() + 
                                      theme_classic() +  
                                      stat_summary(fun.y="mean",position = position_dodge2(width = 0.75)) +
                                      theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank())+ 
                                      theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))+
                                      labs(title="Age = 24 hours (high temp only)", x ="pCO2 level", y = "Larvae size (μm)")+ 
                                      theme(axis.title.y = element_text(size = rel(1.3), angle =90), axis.title.x = element_text(size = rel(1.3), angle = 0))+
                                      theme(axis.text=element_text(size=12)) 

# save the plot 
setwd("C:/Users/samjg/Documents/Github_repositories/Cvirginica_multistressor/RAnalysis")
pdf("Output/Length_Survival/Length_age_8days_Boxplots_hightemp.pdf", width=8, height=6)
print(Age8_ShellLength_Boxplot_hightemp)
dev.off()


```



### Age 11 days ALL DATA  ------------

```{r, LENGTH Age 11 days hours size - all data}


# Age 11 Length mod - all data -------------------------------------------------------------------------------------- #


Age11Length_lme_mod <- lme(length_um~OA*Salinity*Temp,random=~1|random_fact,data=Age11_raw_length)
pander(anova(Age11Length_lme_mod), style='rmarkdown') # anova table of lmer
# |        &nbsp;        | numDF | denDF | F-value |  p-value  |
# |:--------------------:|:-----:|:-----:|:-------:|:---------:|
# |   **(Intercept)**    |   1   |  426  |  766.3  |     0     |
# |        **OA**        |   1   |  13   |  4.216  |  0.06075  |
# |     **Salinity**     |   1   |  13   |  10.09  | 0.007292  |
# |       **Temp**       |   1   |  13   |  21.93  | 0.0004286 |
# |   **OA:Salinity**    |   1   |  13   | 0.3512  |  0.5636   |
# |     **OA:Temp**      |   1   |  13   | 0.9637  |  0.3442   |
# |  **Salinity:Temp**   |   1   |  13   |  12.37  | 0.003786  | **
# | **OA:Salinity:Temp** |   1   |  13   |  0.563  |  0.4664   |
leveneTest(residuals(Age11Length_lme_mod) ~ Age11_raw_length$Temp*Age11_raw_length$OA*Age11_raw_length$Salinity) # < 2.2e-16 ***
boxplot(residuals(Age11Length_lme_mod) ~ Age11_raw_length$Temp*Age11_raw_length$OA*Age11_raw_length$Salinity) # visual of residuals grouped
qqnorm(resid(Age11Length_lme_mod)) # check for normality of residuals - looks okay


# post hoc tests --------------------------------------------------------------------------------------------------- #
posthoc<-emmeans(Age11Length_lme_mod, pairwise~Salinity:Temp, adjust="tukey")
multcomp::cld(posthoc$emmeans,alpha = 0.5, Letters = letters)
 # Salinity Temp emmean    SE df lower.CL upper.CL .group
 # High     Low     104  8.50 13     86.1      123  a    
 # Low      Low     107 12.01 13     81.5      133  a    
 # Low      High    110 12.40 13     83.3      137  a    
 # High     High    172  8.31 13    153.9      190   b  


#  run model (lm)
Age11Length_lm_mod <- lm(length_um~OA*Salinity*Temp,data=Age11_raw_length)
pander(anova(Age11Length_lm_mod), style='rmarkdown') # anova table of lmr
# |        &nbsp;        | Df  | Sum Sq | Mean Sq | F value |  Pr(>F)   |
# |:--------------------:|:---:|:------:|:-------:|:-------:|:---------:|
# |        **OA**        |  1  | 85758  |  85758  |  82.44  | 3.715e-18 |
# |     **Salinity**     |  1  | 104204 | 104204  |  100.2  | 2.227e-21 |
# |       **Temp**       |  1  | 224581 | 224581  |  215.9  | 4.898e-40 |
# |   **OA:Salinity**    |  1  | 28830  |  28830  |  27.72  | 2.204e-07 |
# |     **OA:Temp**      |  1  |  5990  |  5990   |  5.759  |  0.01682  |
# |  **Salinity:Temp**   |  1  | 82062  |  82062  |  78.89  | 1.697e-17 |
# | **OA:Salinity:Temp** |  1  |  1541  |  1541   |  1.482  |  0.2241   |
# |    **Residuals**     | 439 | 456652 |  1040   |   NA    |    NA     |
shapiro.test(residuals(Age11Length_lm_mod)) # 1.24e-08
leveneTest(residuals(Age11Length_lm_mod) ~ Age11_raw_length$Temp*Age11_raw_length$OA*Age11_raw_length$Salinity) # < 2.2e-16 *** pass
boxplot(residuals(Age11Length_lm_mod) ~ Age11_raw_length$Temp*Age11_raw_length$OA*Age11_raw_length$Salinity) # visual of residuals grouped
qqnorm(resid(Age11Length_lm_mod)) # check for normality of residuals - looks okay




# post hoc tests --------------------------------------------------------------------------------------------------- #
posthoc<-emmeans(Age11Length_lm_mod, pairwise~Salinity:Temp, adjust="tukey")
multcomp::cld(posthoc$emmeans,alpha = 0.5, Letters = letters)
 # Salinity Temp emmean   SE  df lower.CL upper.CL .group
 # High     Low     106 2.90 439    100.2      112  a    
 # Low      Low     110 3.65 439    102.3      117  a    
 # Low      High    114 9.54 439     94.9      132  a    
 # High     High    171 2.39 439    165.9      175   b   

# plot the data  ----------------------------------------------------------------------------------------------------- #


require(forcats)
Age11_ShellLength_Boxplot <- ggplot(data=Age11_raw_length, aes(x=fct_relevel(OA, c("Low", "High")), 
                                                             y=length_um, 
                                                             colour=fct_relevel(Salinity, c("Low", "High")), 
                                                             linetype= Temp)) +
                              geom_boxplot() + 
                              theme_bw() +  
                              stat_summary(fun.y="mean",position = position_dodge2(width = 0.75)) +
                              theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank())+ 
                              theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))+
                              labs(title="Age = 11 days", x ="pCO2 level", y = "Shell Length (μm)")+ 
                              theme(axis.title.y = element_text(size = rel(1.3), angle =90), axis.title.x = element_text(size = rel(1.3), angle = 0))+
                              theme(axis.text=element_text(size=12)) 

setwd("C:/Users/samjg/Documents/Github_repositories/Cvirginica_multistressor/RAnalysis")
pdf("Output/Length_Survival/Length_age_11days_Boxplots.pdf", width=11, height=6)
print(Age11_ShellLength_Boxplot)
dev.off()

```


### Age 15 days ALL DATA  ------------

```{r, LENGTH Age 15 days hours size - all data}


# Age 15 Length mod - all data -------------------------------------------------------------------------------------- #

library(lme4)
library(lmerTest)
Age15Length_lme_mod <- lmer(length_um~OA*Salinity*Temp+(1|random_fact),na.action = na.exclude,data=Age15_raw_length)
anova(Age15Length_lme_mod)
# Type III Analysis of Variance Table with Satterthwaite's method
#                  Sum Sq Mean Sq NumDF   DenDF F value    Pr(>F)    
# OA                 9550    9550     1 10.3987  4.9471   0.04935 *  
# Salinity          19553   19553     1 10.5734 10.1289   0.00914 ** 
# Temp             161985  161985     1  9.6591 83.9116 4.516e-06 ***
# OA:Salinity          16      16     1 10.4108  0.0085   0.92828    
# OA:Temp            1355    1355     1  9.1807  0.7020   0.42340    
# Salinity:Temp     12445   12445     1  9.9323  6.4469   0.02955 *  
leveneTest(residuals(Age15Length_lme_mod) ~ Age15_raw_length$Temp*Age15_raw_length$OA*Age15_raw_length$Salinity) # < 2.2e-16 *** pass
boxplot(residuals(Age15Length_lme_mod) ~ Age15_raw_length$Temp*Age15_raw_length$OA*Age15_raw_length$Salinity) # visual of residuals grouped
qqnorm(resid(Age15Length_lme_mod)) # check for normality of residuals - looks okay
# post hoc tests --------------------------------------------------------------------------------------------------- #
posthoc<-emmeans(Age15Length_lme_mod, pairwise~Salinity:Temp, adjust="tukey")
multcomp::cld(posthoc$emmeans,alpha = 0.5, Letters = letters)
 # Salinity Temp emmean   SE    df lower.CL upper.CL .group
 # High     Low     121 12.9  9.81     91.9      150  a    
 # Low      High    191 15.6 11.68    157.3      226   b   
 # High     High    275 10.3  8.98    252.1      299    c  
 # Low      Low  nonEst   NA    NA       NA       NA       

x <- ( (275 - 121) / 275)*100
x

#  run model (lm)
Age15Length_lm_mod <- lm(length_um~OA*Salinity*Temp,data=Age15_raw_length)
pander(anova(Age15Length_lm_mod), style='rmarkdown') # anova table of lmr
# |      &nbsp;       | Df  | Sum Sq  | Mean Sq | F value |  Pr(>F)   |
# |:-----------------:|:---:|:-------:|:-------:|:-------:|:---------:|
# |      **OA**       |  1  |  1921   |  1921   | 0.8595  |  0.3546   |
# |   **Salinity**    |  1  | 108453  | 108453  |  48.53  | 1.828e-11 |
# |     **Temp**      |  1  | 1312117 | 1312117 |  587.2  | 1.198e-74 |
# |  **OA:Salinity**  |  1  |  10811  |  10811  |  4.838  |  0.02855  |
# |    **OA:Temp**    |  1  |   421   |   421   | 0.1884  |  0.6646   |
# | **Salinity:Temp** |  1  |  53196  |  53196  |  23.81  | 1.677e-06 |
# |   **Residuals**   | 323 | 721778  |  2235   |   NA    |    NA     |
shapiro.test(residuals(Age15Length_lm_mod)) # 0.18815
leveneTest(residuals(Age15Length_lm_mod) ~ Age15_raw_length$Temp*Age15_raw_length$OA*Age15_raw_length$Salinity) # 0.11596 pass
boxplot(residuals(Age15Length_lm_mod) ~ Age15_raw_length$Temp*Age15_raw_length$OA*Age15_raw_length$Salinity) # visual of residuals grouped
qqnorm(resid(Age15Length_lm_mod)) # check for normality of residuals - looks okay




# post hoc tests --------------------------------------------------------------------------------------------------- #
posthoc<-emmeans(Age15Length_lm_mod, pairwise~OA:Salinity:Temp, adjust="tukey")
multcomp::cld(posthoc$emmeans,alpha = 0.5, Letters = letters)
 # OA   Salinity Temp emmean   SE  df lower.CL upper.CL .group
 # High Low      Low    72.5 1.30 3915     69.9     75.1  a    
 # High Low      High   73.2 1.57 3915     70.1     76.2  a    
 # High High     High   76.1 1.28 3915     73.6     78.6  a    
 # Low  Low      Low    80.9 1.07 3915     78.8     83.0   b   
 # Low  High     Low    83.2 1.11 3915     81.0     85.15   bc  
 # High High     Low    83.2 1.215 3915     80.8     85.7   bc  
 # Low  Low      High   85.5 1.16 3915     83.2     87.8    c  
 # Low  High     High   92.1 1.33 3915     89.5     915.7     d 

# plot the data  ----------------------------------------------------------------------------------------------------- #


require(forcats)
Age15_ShellLength_Boxplot <- ggplot(data=Age15_raw_length, aes(x=fct_relevel(OA, c("Low", "High")), 
                                                             y=length_um, 
                                                             colour=fct_relevel(Salinity, c("Low", "High")), 
                                                             linetype= Temp)) +
                              geom_boxplot() + 
                              theme_bw() +  
                              stat_summary(fun.y="mean",position = position_dodge2(width = 0.75)) +
                              theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank())+ 
                              theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))+
                              labs(title="Age = 15 days", x ="pCO2 level", y = "Shell Length (μm)")+ 
                              theme(axis.title.y = element_text(size = rel(1.3), angle =90), axis.title.x = element_text(size = rel(1.3), angle = 0))+
                              theme(axis.text=element_text(size=12)) 

setwd("C:/Users/samjg/Documents/Github_repositories/Cvirginica_multistressor/RAnalysis")
pdf("Output/Length_Survival/Length_age_15days_Boxplots.pdf", width=15, height=6)
print(Age15_ShellLength_Boxplot)
dev.off()

```



:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
# Survival ::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::  :::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::


### Age 24 hours ALL DATA ------------

```{r SURVIVAL Age 24 hours - all data}
age_1<- Av_length.survival_dat %>%
          filter(Day=="1")


# Age 1 Length mod - all data -------------------------------------------------------------------------------------- #


Age1_Survival_lme_mod <- lme(Survival~OA*Salinity*Temp,random=~1|random_fact,data=age_1)
pander(anova(Age1_Survival_lme_mod), style='rmarkdown') # anova table of lmer
# |        &nbsp;        | numDF | denDF | F-value |  p-value  |
# |:--------------------:|:-----:|:-----:|:-------:|:---------:|
# |   **(Intercept)**    |   1   |  16   |  1835   |     0     |
# |        **OA**        |   1   |  16   |  10.28  | 0.005513  | *
# |     **Salinity**     |   1   |  16   |  1.647  |  0.2176   |
# |       **Temp**       |   1   |  16   |  22.72  | 0.0002102 | *
# |   **OA:Salinity**    |   1   |  16   |  7.528  |  0.01442  | *
# |     **OA:Temp**      |   1   |  16   |  2.487  |  0.1344   |
# |  **Salinity:Temp**   |   1   |  16   |  2.07   |  0.1695   |
# | **OA:Salinity:Temp** |   1   |  16   |  3.096  |  0.09758  |
leveneTest(residuals(Age1_Survival_lme_mod) ~ age_1$Temp*age_1$OA*age_1$Salinity) # 0.8279- pass
boxplot(residuals(Age1_Survival_lme_mod) ~ age_1$Temp*age_1$OA*age_1$Salinity) # visual of residuals grouped
qqnorm(resid(Age1_Survival_lme_mod)) # check for normality of residuals - looks okay





Age1_Survival_lm_mod <- lm(Survival~OA*Salinity*Temp,data=age_1)
pander(anova(Age1_Survival_lm_mod), style='rmarkdown') # anova table of lmr
# |        &nbsp;        | Df |  Sum Sq  | Mean Sq  | F value |  Pr(>F)   |
# |:--------------------:|:--:|:--------:|:--------:|:-------:|:---------:|
# |        **OA**        | 1  | 0.02837  | 0.02837  |  10.28  | 0.005513  |
# |     **Salinity**     | 1  | 0.004548 | 0.004548 |  1.647  |  0.2176   |
# |       **Temp**       | 1  | 0.06273  | 0.06273  |  22.72  | 0.0002102 |
# |   **OA:Salinity**    | 1  | 0.02079  | 0.02079  |  7.528  |  0.01442  |
# |     **OA:Temp**      | 1  | 0.006866 | 0.006866 |  2.487  |  0.1344   |
# |  **Salinity:Temp**   | 1  | 0.005716 | 0.005716 |  2.07   |  0.1695   |
# | **OA:Salinity:Temp** | 1  | 0.008549 | 0.008549 |  3.096  |  0.09758  |
# |    **Residuals**     | 16 | 0.04418  | 0.002761 |   NA    |    NA     |
shapiro.test(residuals(Age1_Survival_lm_mod)) #0.156
leveneTest(residuals(Age1_Survival_lm_mod) ~ age_1$Temp*age_1$OA*age_1$Salinity) # 0.8279- pass
boxplot(residuals(Age1_Survival_lm_mod) ~ age_1$Temp*age_1$OA*age_1$Salinity) # visual of residuals grouped
qqnorm(resid(Age1_Survival_lm_mod)) # check for normality of residuals - looks okay




# post hoc tests --------------------------------------------------------------------------------------------------- #
posthoc<-emmeans(Age1_Survival_lme_mod, pairwise~OA:Salinity, adjust="tukey")
multcomp::cld(posthoc$emmeans,alpha = 0.5, Letters = letters)
#  OA   Salinity emmean     SE df lower.CL upper.CL .group
#  High Low       0.382 0.0215 16    0.336    0.427  a    
#  High High      0.468 0.0215 16    0.423    0.514   b   
#  Low  High      0.478 0.0215 16    0.433    0.524   b   
#  Low  Low       0.509 0.0215 16    0.464    0.555   b 



# plot the data  ----------------------------------------------------------------------------------------------------- #
Age1_Survival_Boxplot_2 <- age_1 %>% 
  dplyr::group_by(OA,Salinity, Temp) %>% 
  dplyr::summarise(mean_surv = mean(Survival), 
                   n         = n(),
                   sd_surv   = sd(Survival),
                   se_surv   = sd_surv/(sqrt(n))) %>% 
                              ggplot(aes(x=fct_relevel(OA, c("Low", "High")), 
                                                             y=mean_surv, 
                                                             colour=fct_relevel(Salinity, c("Low", "High")), 
                                                             linetype = Temp)) +
                              geom_point(aes (fill = fct_relevel(Salinity, c("Low", "High")), shape = Temp), position = "dodge2") +
                              geom_errorbar(aes(ymin = mean_surv - se_surv, 
                                                ymax = mean_surv + se_surv,
                                                fill = fct_relevel(Salinity, c("Low", "High"))), 
                                                width = 0.5, position= "dodge2") +
                              theme_classic() +  
                              ylim(0.2,0.6) +
                              theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank())+ 
                              theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))+
                              labs(title="Age = 24 hours", x ="pCO2 level", y = "Survival")+ 
                              theme(axis.title.y = element_text(size = rel(1.3), angle =90), axis.title.x = element_text(size = rel(1.3), angle = 0))+
                              theme(axis.text=element_text(size=12)) 

setwd("C:/Users/samjg/Documents/Github_repositories/Cvirginica_multistressor/RAnalysis")
pdf("Output/Length_Survival/Survival_age_24hrs_MeanSE.pdf", width=8, height=6)
print(Age1_Survival_Boxplot_2)
dev.off()

Age1_Survival_Boxplot <-ggplot(data=age_1, aes(x=fct_relevel(OA, c("Low", "High")), 
                                        y=Survival, 
                                        colour=fct_relevel(Salinity, c("Low", "High")), 
                                        linetype = Temp)) +
                                          geom_boxplot() + 
                                          theme_classic() +  
                                          geom_jitter(position = position_dodge2(width = 0.75))+                                         # ylim(0.2,0.6) +
                                          stat_summary(fun.y="mean",position = position_dodge2(width = 0.75)) +
                                          theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank())+ 
                                          theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))+
                                          labs(title="Age = 24 hours (all data)", 
                                               x ="pCO2 level", 
                                               y = expression(Respiration~rate~"("~ng~L^{-1}~O[2]%.%indiv^{-1}%.% hr^{-1}~")")) + 
                                          theme(axis.title.y = element_text(size = rel(1.3), angle =90), 
                                                axis.title.x = element_text(size = rel(1.3), angle = 0)) +
                                          theme(axis.text=element_text(size=12)) 
  
setwd("C:/Users/samjg/Documents/Github_repositories/Cvirginica_multistressor/RAnalysis")
pdf("Output/Length_Survival/Survival_age_24hrs.pdf", width=8, height=6)
print(Age1_Survival_Boxplot)
dev.off()
```


### Age 24 hours HIGH TEMP ONLY ------------

```{r, SURVIVAL Age 24 hours - HIGH TEMP ONLY}
age_1_hightemp <- Av_length.survival_dat %>%
                      filter(Day=="1") %>% 
                      dplyr::filter(Temp %in% 'High')


# Age 1 Length mod - all data -------------------------------------------------------------------------------------- #


Age1_Survival_lme_mod_hightemp <- lme(Survival~OA*Salinity,random=~1|random_fact,data=age_1_hightemp)
pander(anova(Age1_Survival_lme_mod_hightemp), style='rmarkdown') # anova table of lmer
# |     &nbsp;      | numDF | denDF | F-value |  p-value  |
# |:---------------:|:-----:|:-----:|:-------:|:---------:|
# | **(Intercept)** |   1   |   8   |  2296   | 3.977e-11 |
# |     **OA**      |   1   |   8   |  23.18  |  0.00133  | * main effect of OA 
# |  **Salinity**   |   1   |   8   | 0.02447 |  0.8796   |
# | **OA:Salinity** |   1   |   8   | 0.9816  |  0.3508   |
leveneTest(residuals(Age1_Survival_lme_mod_hightemp) ~ age_1_hightemp$OA*age_1_hightemp$Salinity) # 0.5608- pass
boxplot(residuals(Age1_Survival_lme_mod_hightemp) ~ age_1_hightemp$OA*age_1_hightemp$Salinity) # visual of residuals grouped
qqnorm(resid(Age1_Survival_lme_mod_hightemp)) # check for normality of residuals - looks okay


# lm model
Age1_Survival_lm_mod_hightemp <- lm(Survival~OA*Salinity,data=age_1_hightemp)
pander(anova(Age1_Survival_lm_mod_hightemp), style='rmarkdown') # anova table of lm
# |     &nbsp;      | Df |  Sum Sq   |  Mean Sq  | F value | Pr(>F)  |
# |:---------------:|:--:|:---------:|:---------:|:-------:|:-------:|
# |     **OA**      | 1  |  0.03158  |  0.03158  |  23.18  | 0.00133 | * main effect of OA 
# |  **Salinity**   | 1  | 3.333e-05 | 3.333e-05 | 0.02447 | 0.8796  |
# | **OA:Salinity** | 1  | 0.001337  | 0.001337  | 0.9816  | 0.3508  |
# |  **Residuals**  | 8  |  0.0109   | 0.001362  |   NA    |   NA    |
shapiro.test(residuals(Age1_Survival_lm_mod_hightemp)) # 0.7963
leveneTest(residuals(Age1_Survival_lm_mod_hightemp) ~ age_1_hightemp$OA*age_1_hightemp$Salinity) # 0.5608- pass
boxplot(residuals(Age1_Survival_lm_mod_hightemp) ~ age_1_hightemp$OA*age_1_hightemp$Salinity) # visual of residuals grouped
qqnorm(resid(Age1_Survival_lm_mod_hightemp)) # check for normality of residuals - looks okay


# post hoc tests --------------------------------------------------------------------------------------------------- #

posthoc<-lsmeans(Age1_Survival_lme_mod_hightemp, ~OA, adjust="tukey")
posthoc<-emmeans(Age1_Survival_lme_mod_hightemp, pairwise~OA, adjust="tukey")

multcomp::cld(posthoc$emmeans,alpha = 0.5, Letters = letters)
 # OA   emmean     SE df lower.CL upper.CL .group
 # High  0.459 0.0151  8    0.425    0.494  a    
 # Low   0.562 0.0151  8    0.527    0.597   b 



# plot the data  ----------------------------------------------------------------------------------------------------- #



Age1_Survival_Boxplot_2 <- age_1_hightemp %>% 
  dplyr::group_by(OA,Salinity) %>% 
  dplyr::summarise(mean_surv = mean(Survival), 
                   n         = n(),
                   sd_surv   = sd(Survival),
                   se_surv   = sd_surv/(sqrt(n))) %>% 
                              ggplot(aes(x=fct_relevel(OA, c("Low", "High")), 
                                                             y=mean_surv, 
                                                             colour=fct_relevel(Salinity, c("Low", "High"))))+
                              geom_point(aes (fill = fct_relevel(Salinity, c("Low", "High"))), position = "dodge2") +
                              geom_errorbar(aes(ymin = mean_surv - se_surv, 
                                                ymax = mean_surv + se_surv,
                                                fill = fct_relevel(Salinity, c("Low", "High"))), 
                                                width = 0.5, position= "dodge2") +
                              theme_classic() +  
                              ylim(0.2,0.6) +
                              theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank())+ 
                              theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))+
                              labs(title="Age = 24 hours", x ="pCO2 level", y = "Survival")+ 
                              theme(axis.title.y = element_text(size = rel(1.3), 
                                                                angle =90), 
                                                                axis.title.x = element_text(size = rel(1.3), 
                                                                angle = 0)) +
                              theme(axis.text=element_text(size=12)) 

setwd("C:/Users/samjg/Documents/Github_repositories/Cvirginica_multistressor/RAnalysis")
pdf("Output/Length_Survival/Survival_age_24hrs_MeanSE_hightemp.pdf", width=8, height=6)
print(Age1_Survival_Boxplot_2)
dev.off()
 
Age1_Survival_Boxplot <-ggplot(data=age_1_hightemp, aes(x=fct_relevel(OA, c("Low", "High")), 
                                        y=Survival, 
                                        colour=fct_relevel(Salinity, c("Low", "High")), 
                                        linetype = Temp)) +
                                          geom_boxplot() + 
                                          theme_classic() +  
                                          geom_jitter(position = position_dodge2(width = 0.75))+                                         # ylim(0.2,0.6) +
                                          stat_summary(fun.y="mean",position = position_dodge2(width = 0.75)) +
                                          theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank())+ 
                                          theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))+
                                          labs(title="Age = 24 hours (all data)", 
                                               x ="pCO2 level", 
                                               y = expression(Respiration~rate~"("~ng~L^{-1}~O[2]%.%indiv^{-1}%.% hr^{-1}~")")) + 
                                          theme(axis.title.y = element_text(size = rel(1.3), angle =90), 
                                                axis.title.x = element_text(size = rel(1.3), angle = 0)) +
                                          theme(axis.text=element_text(size=12)) 
  
setwd("C:/Users/samjg/Documents/Github_repositories/Cvirginica_multistressor/RAnalysis")
pdf("Output/Length_Survival/Survival_age_24hrs_hightemp.pdf", width=8, height=6)
print(Age1_Survival_Boxplot)
dev.off()

```



### Age 4 days ALL DATA  ------------

```{r, SURVIVAL Age 4 days - all data}
age_4<- Av_length.survival_dat%>%
  filter(Day=="4") %>% 
  arrange(Survival) %>% 
  mutate(Survival = ifelse(Survival == last(Survival), 0.75, Survival)) # ID #12 was 0.46 -  whereas survival on day 4 was 0.75 - this is an artifact of increased numbers? I changed to 0.75 to reflect no losses between days 4 and 4


# Age 4 Length mod - all data -------------------------------------------------------------------------------------- #


Age4_Survival_lme_mod <- lme(Survival~OA*Salinity*Temp,random=~1|random_fact,data=age_4)
pander(anova(Age4_Survival_lme_mod), style='rmarkdown') # anova table of lm
# |        &nbsp;        | numDF | denDF | F-value |  p-value  |
# |:--------------------:|:-----:|:-----:|:-------:|:---------:|
# |   **(Intercept)**    |   1   |  16   |  188.3  | 2.878e-10 |
# |        **OA**        |   1   |  16   |  1.342  |  0.2638   |
# |     **Salinity**     |   1   |  16   |  9.182  | 0.007963  | * 
# |       **Temp**       |   1   |  16   |  3.637  |  0.07464  | 
# |   **OA:Salinity**    |   1   |  16   | 0.5783  |   0.458   |
# |     **OA:Temp**      |   1   |  16   |  1.396  |  0.2546   |
# |  **Salinity:Temp**   |   1   |  16   | 0.06036 |   0.809   |
# | **OA:Salinity:Temp** |   1   |  16   | 0.2301  |   0.638   |
leveneTest(residuals(Age4_Survival_lme_mod) ~ age_4$Temp*age_4$OA*age_4$Salinity) # 0.712 pass
boxplot(residuals(Age4_Survival_lme_mod) ~ age_4$Temp*age_4$OA*age_4$Salinity) # visual of residuals grouped
qqnorm(resid(Age4_Survival_lme_mod)) # check for normality of residuals - looks okay


# run mod (lm model) 
Age4_Survival_lm_mod <- lm(Survival~OA*Salinity*Temp,data=age_4)
pander(anova(Age4_Survival_lm_mod), style='rmarkdown') # anova table of lm
# |        &nbsp;        | Df |  Sum Sq  | Mean Sq  | F value |  Pr(>F)  |
# |:--------------------:|:--:|:--------:|:--------:|:-------:|:--------:|
# |        **OA**        | 1  | 0.04084  | 0.04084  |  1.342  |  0.2638  |
# |     **Salinity**     | 1  |  0.2795  |  0.2795  |  9.182  | 0.007963 |
# |       **Temp**       | 1  |  0.1107  |  0.1107  |  3.637  | 0.07464  |
# |   **OA:Salinity**    | 1  |  0.0176  |  0.0176  | 0.5783  |  0.458   |
# |     **OA:Temp**      | 1  |  0.0425  |  0.0425  |  1.396  |  0.2546  |
# |  **Salinity:Temp**   | 1  | 0.001837 | 0.001837 | 0.06036 |  0.809   |
# | **OA:Salinity:Temp** | 1  | 0.007004 | 0.007004 | 0.2301  |  0.638   |
# |    **Residuals**     | 16 |  0.4871  | 0.03044  |   NA    |    NA    |
library(stats)
shapiro.test(residuals(Age4_Survival_lm_mod)) # 0.2763 pass
leveneTest(residuals(Age4_Survival_lm_mod) ~ age_4$Temp*age_4$OA*age_4$Salinity) # 0.712 pass
boxplot(residuals(Age4_Survival_lm_mod) ~ age_4$Temp*age_4$OA*age_4$Salinity) # visual of residuals grouped
qqnorm(resid(Age4_Survival_lm_mod)) # check for normality of residuals - looks okay





# post hoc tests --------------------------------------------------------------------------------------------------- #

posthoc<-emmeans(Age4_Survival_lm_mod, pairwise~Salinity, adjust="tukey")

multcomp::cld(posthoc$emmeans,alpha = 0.5, Letters = letters)
# Salinity emmean     SE df lower.CL upper.CL .group
#  Low       0.381 0.0504 16    0.274    0.488  a    
#  High      0.597 0.0504 16    0.490    0.703   b 
#36.1% higher under high salinity

# plot the data  ----------------------------------------------------------------------------------------------------- #
Age4_Survival_Boxplot_2 <- age_4 %>% 
  dplyr::group_by(OA,Salinity, Temp) %>% 
  dplyr::summarise(mean_surv = mean(Survival), 
                   n         = n(),
                   sd_surv   = sd(Survival),
                   se_surv   = sd_surv/(sqrt(n))) %>% 
                              ggplot(aes(x=fct_relevel(OA, c("Low", "High")), 
                                                             y=mean_surv, 
                                                             colour=fct_relevel(Salinity, c("Low", "High")), 
                                                             linetype = Temp)) +
                              geom_point(aes (fill = fct_relevel(Salinity, c("Low", "High")), shape = Temp), position = "dodge2") +
                              geom_errorbar(aes(ymin = mean_surv - se_surv, ymax = mean_surv + se_surv), width = 0.5, position= "dodge2") +
                              theme_classic() +  
                              #ylim(0,0.75) +
                              theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank())+ 
                              theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))+
                              labs(title="Age = 4 days", x ="pCO2 level", y = "Survival")+ 
                              theme(axis.title.y = element_text(size = rel(1.3), angle =90), axis.title.x = element_text(size = rel(1.3), angle = 0))+
                              theme(axis.text=element_text(size=12)) 

setwd("C:/Users/samjg/Documents/Github_repositories/Cvirginica_multistressor/RAnalysis")
pdf("Output/Length_Survival/Survival_age_4days_MeanSE.pdf", width=4, height=6)
print(Age4_Survival_Boxplot_2)
dev.off()




##Here Low Salinity treatments are in Blue
Age4_Survival_Boxplot <-ggplot(data=age_4, aes(x=fct_relevel(OA, c("Low", "High")), 
                                        y=Survival, 
                                        colour=fct_relevel(Salinity, c("Low", "High")), 
                                        linetype = Temp)) +
                                          geom_boxplot() + 
                                          theme_classic() +  
                                          geom_jitter(position = position_dodge2(width = 0.75))+
                                          ylim(0,0.75) +
                                          stat_summary(fun.y="mean",position = position_dodge2(width = 0.75)) +
                                          theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank())+ 
                                          theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))+
                                          labs(title="Age = 4 days (all data)", 
                                               x ="pCO2 level", 
                                               y = expression(Respiration~rate~"("~ng~L^{-1}~O[2]%.%indiv^{-1}%.% hr^{-1}~")")) + 
                                          theme(axis.title.y = element_text(size = rel(1.3), angle =90), 
                                                axis.title.x = element_text(size = rel(1.3), angle = 0)) +
                                          theme(axis.text=element_text(size=12)) 

setwd("C:/Users/samjg/Documents/Github_repositories/Cvirginica_multistressor/RAnalysis")
pdf("Output/Length_Survival/Survival_age_4days.pdf", width=4, height=6)
print(Age4_Survival_Boxplot)
dev.off()

```


### Age 8 days ALL DATA  ------------

```{r, SURVIVAL Age 8 days - all data}
age_8<- Av_length.survival_dat%>%
  filter(Day=="8") %>% 
  arrange(Survival) %>% 
  mutate(Survival = ifelse(Survival == last(Survival), 0.75, Survival)) # ID #12 was 0.86 -  whereas survival on day 4 was 0.75 - this is an artifact of increased numbers? I changed to 0.75 to reflect no losses between days 4 and 8


# Age 8 Length mod - all data -------------------------------------------------------------------------------------- #


Age8_Survival_lme_mod <- lme(Survival~OA*Salinity*Temp,random=~1|random_fact,data=age_8)
pander(anova(Age8_Survival_lme_mod), style='rmarkdown') # anova table of lm
# |        &nbsp;        | numDF | denDF | F-value |  p-value  |
# |:--------------------:|:-----:|:-----:|:-------:|:---------:|
# |   **(Intercept)**    |   1   |  16   |  46.08  | 4.355e-06 |
# |        **OA**        |   1   |  16   | 0.3291  |  0.5742   |
# |     **Salinity**     |   1   |  16   |  14.26  | 0.001652  | *
# |       **Temp**       |   1   |  16   |  0.028  |  0.8692   |
# |   **OA:Salinity**    |   1   |  16   |  0.112  |  0.7422   |
# |     **OA:Temp**      |   1   |  16   | 0.06913 |   0.796   |
# |  **Salinity:Temp**   |   1   |  16   | 0.1651  |  0.6899   |
# | **OA:Salinity:Temp** |   1   |  16   | 0.4805  |  0.4981   |
leveneTest(residuals(Age8_Survival_lme_mod) ~ age_8$Temp*age_8$OA*age_8$Salinity) # 0.41 pass
boxplot(residuals(Age8_Survival_lme_mod) ~ age_8$Temp*age_8$OA*age_8$Salinity) # visual of residuals grouped
qqnorm(resid(Age8_Survival_lme_mod)) # check for normality of residuals - looks okay


# run mod (lm model) 
Age8_Survival_lm_mod <- lm(Survival~OA*Salinity*Temp,data=age_8)
pander(anova(Age8_Survival_lm_mod), style='rmarkdown') # anova table of lm
# |        &nbsp;        | Df |  Sum Sq   |  Mean Sq  | F value |  Pr(>F)  |
# |:--------------------:|:--:|:---------:|:---------:|:-------:|:--------:|
# |        **OA**        | 1  |  0.0096   |  0.0096   | 0.3291  |  0.5742  |
# |     **Salinity**     | 1  |  0.4161   |  0.4161   |  14.26  | 0.001652 | *
# |       **Temp**       | 1  | 0.0008167 | 0.0008167 |  0.028  |  0.8692  |
# |   **OA:Salinity**    | 1  | 0.003267  | 0.003267  |  0.112  |  0.7422  |
# |     **OA:Temp**      | 1  | 0.002017  | 0.002017  | 0.06913 |  0.796   |
# |  **Salinity:Temp**   | 1  | 0.004817  | 0.004817  | 0.1651  |  0.6899  |
# | **OA:Salinity:Temp** | 1  |  0.01402  |  0.01402  | 0.4805  |  0.4981  |
# |    **Residuals**     | 16 |  0.4667   |  0.02917  |   NA    |    NA    |
library(stats)
shapiro.test(residuals(Age8_Survival_lm_mod)) # 0.1911 pass
leveneTest(residuals(Age8_Survival_lm_mod) ~ age_8$Temp*age_8$OA*age_8$Salinity) # 0.41 pass
boxplot(residuals(Age8_Survival_lm_mod) ~ age_8$Temp*age_8$OA*age_8$Salinity) # visual of residuals grouped
qqnorm(resid(Age8_Survival_lm_mod)) # check for normality of residuals - looks okay





# post hoc tests --------------------------------------------------------------------------------------------------- #

posthoc<-emmeans(Age8_Survival_lm_mod, pairwise~Salinity, adjust="tukey")

multcomp::cld(posthoc$emmeans,alpha = 0.5, Letters = letters)
 # Salinity emmean     SE df lower.CL upper.CL .group
 # Low       0.105 0.0493 16  0.00048    0.210  a    
 # High      0.368 0.0493 16  0.26381    0.473   b  
#71.4% higher under high salinity

# plot the data  ----------------------------------------------------------------------------------------------------- #
Age8_Survival_Boxplot_2 <- age_8 %>% 
  dplyr::group_by(OA,Salinity, Temp) %>% 
  dplyr::summarise(mean_surv = mean(Survival), 
                   n         = n(),
                   sd_surv   = sd(Survival),
                   se_surv   = sd_surv/(sqrt(n))) %>% 
                              ggplot(aes(x=fct_relevel(OA, c("Low", "High")), 
                                                             y=mean_surv, 
                                                             colour=fct_relevel(Salinity, c("Low", "High")), 
                                                             linetype = Temp)) +
                              geom_point(aes (fill = fct_relevel(Salinity, c("Low", "High")), shape = Temp), position = "dodge2") +
                              geom_errorbar(aes(ymin = mean_surv - se_surv, ymax = mean_surv + se_surv), width = 0.5, position= "dodge2") +
                              theme_classic() +  
                              #ylim(0,0.75) +
                              theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank())+ 
                              theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))+
                              labs(title="Age = 8 days", x ="pCO2 level", y = "Survival")+ 
                              theme(axis.title.y = element_text(size = rel(1.3), angle =90), axis.title.x = element_text(size = rel(1.3), angle = 0))+
                              theme(axis.text=element_text(size=12)) 

setwd("C:/Users/samjg/Documents/Github_repositories/Cvirginica_multistressor/RAnalysis")
pdf("Output/Length_Survival/Survival_age_8days_MeanSE.pdf", width=8, height=6)
print(Age8_Survival_Boxplot_2)
dev.off()




##Here Low Salinity treatments are in Blue
Age8_Survival_Boxplot <-ggplot(data=age_8, aes(x=fct_relevel(OA, c("Low", "High")), 
                                        y=Survival, 
                                        colour=fct_relevel(Salinity, c("Low", "High")), 
                                        linetype = Temp)) +
                                          geom_boxplot() + 
                                          theme_classic() +  
                                          geom_jitter(position = position_dodge2(width = 0.75))+
                                          ylim(0,0.75) +
                                          stat_summary(fun.y="mean",position = position_dodge2(width = 0.75)) +
                                          theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank())+ 
                                          theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))+
                                          labs(title="Age = 24 hours (all data)", 
                                               x ="pCO2 level", 
                                               y = expression(Respiration~rate~"("~ng~L^{-1}~O[2]%.%indiv^{-1}%.% hr^{-1}~")")) + 
                                          theme(axis.title.y = element_text(size = rel(1.3), angle =90), 
                                                axis.title.x = element_text(size = rel(1.3), angle = 0)) +
                                          theme(axis.text=element_text(size=12)) 

setwd("C:/Users/samjg/Documents/Github_repositories/Cvirginica_multistressor/RAnalysis")
pdf("Output/Length_Survival/Survival_age_8days.pdf", width=8, height=6)
print(Age8_Survival_Boxplot)
dev.off()

```


### Age 8 days HIGH TEMP ONLY ------------

```{r, SURVIVAL Age 8 days - HIGH TEMP ONLY}
age_8_hightemp <- Av_length.survival_dat %>%
                      filter(Day=="8") %>% 
                      dplyr::filter(Temp %in% 'High')


# Age 1 Length mod - all data -------------------------------------------------------------------------------------- #


Age8_Survival_lme_mod_hightemp <- lme(Survival~OA*Salinity,random=~1|random_fact,data=age_8_hightemp)
pander(anova(Age8_Survival_lme_mod_hightemp), style='rmarkdown') # anova table of lmer
# |     &nbsp;      | numDF | denDF | F-value |  p-value  |
# |:---------------:|:-----:|:-----:|:-------:|:---------:|
# | **(Intercept)** |   1   |   8   |  57.6   | 6.366e-05 |
# |     **OA**      |   1   |   8   | 0.1269  |  0.7309   |
# |  **Salinity**   |   1   |   8   |  14.93  | 0.004786  |
# | **OA:Salinity** |   1   |   8   |  1.388  |  0.2726   |
leveneTest(residuals(Age8_Survival_lme_mod_hightemp) ~ age_8_hightemp$OA*age_8_hightemp$Salinity) # 0.7127- pass
boxplot(residuals(Age8_Survival_lm_mod_hightemp) ~ age_8_hightemp$OA*age_8_hightemp$Salinity) # visual of residuals grouped
qqnorm(resid(Age8_Survival_lm_mod_hightemp)) # check for normality of residuals - looks okay






# run modle (lm)
Age8_Survival_lm_mod_hightemp <- lm(Survival~OA*Salinity,data=age_8_hightemp)
pander(anova(Age8_Survival_lm_mod_hightemp), style='rmarkdown') # anova table of lmer
#      &nbsp;      | Df |  Sum Sq  | Mean Sq  | F value |  Pr(>F)  |
# |:---------------:|:--:|:--------:|:--------:|:-------:|:--------:|
# |     **OA**      | 1  | 0.001408 | 0.001408 | 0.1269  |  0.7309  |
# |  **Salinity**   | 1  |  0.1657  |  0.1657  |  14.93  | 0.004786 |
# | **OA:Salinity** | 1  | 0.01541  | 0.01541  |  1.388  |  0.2726  |
# |  **Residuals**  | 8  |  0.0888  |  0.0111  |   NA    |    NA    |
shapiro.test(residuals(Age8_Survival_lm_mod_hightemp)) # 0.8541
leveneTest(residuals(Age8_Survival_lm_mod_hightemp) ~ age_8_hightemp$OA*age_8_hightemp$Salinity) # 0.7127- pass
boxplot(residuals(Age8_Survival_lm_mod_hightemp) ~ age_1_hightemp$OA*age_1_hightemp$Salinity) # visual of residuals grouped
qqnorm(resid(Age8_Survival_lm_mod_hightemp)) # check for normality of residuals - looks okay


# post hoc tests --------------------------------------------------------------------------------------------------- #

posthoc<-lsmeans(Age8_Survival_lme_mod_hightemp, ~Salinity, adjust="tukey")
posthoc<-emmeans(Age8_Survival_lme_mod_hightemp, pairwise~Salinity, adjust="tukey")

multcomp::cld(posthoc$emmeans,alpha = 0.5, Letters = letters)
# Salinity emmean     SE df lower.CL upper.CL .group
#  Low      0.0683 0.0635  6  -0.0871    0.224  a    
#  High     0.3483 0.0449  6   0.2384    0.458   b   



# plot the data  ----------------------------------------------------------------------------------------------------- #



Age8_Survival_Boxplot <- age_8_hightemp %>% 
  dplyr::group_by(OA,Salinity) %>% 
  dplyr::summarise(mean_surv = mean(Survival), 
                   n         = n(),
                   sd_surv   = sd(Survival),
                   se_surv   = sd_surv/(sqrt(n))) %>% 
                              ggplot(aes(x=fct_relevel(OA, c("Low", "High")), 
                                                             y=mean_surv, 
                                                             colour=fct_relevel(Salinity, c("Low", "High"))))+
                              geom_point(aes (fill = fct_relevel(Salinity, c("Low", "High"))), position = "dodge2") +
                              geom_errorbar(aes(ymin = mean_surv - se_surv, 
                                                ymax = mean_surv + se_surv,
                                                fill = fct_relevel(Salinity, c("Low", "High"))), 
                                                width = 0.5, position= "dodge2") +
                              theme_classic() +  
                              #ylim(0.2,0.6) +
                              theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank())+ 
                              theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))+
                              labs(title="Age = 8 days (high temp only)", x ="pCO2 level", y = "Survival")+ 
                              theme(axis.title.y = element_text(size = rel(1.3), 
                                                                angle =90), 
                                                                axis.title.x = element_text(size = rel(1.3), 
                                                                angle = 0)) +
                              theme(axis.text=element_text(size=12)) 

setwd("C:/Users/samjg/Documents/Github_repositories/Cvirginica_multistressor/RAnalysis")
pdf("Output/Length_Survival/Survival_age_24hrs_MeanSE_hightemp.pdf", width=8, height=6)
print(Age8_Survival_Boxplot)
dev.off()



Age8_Survival_Boxplot <-ggplot(data=age_8_hightemp, aes(x=fct_relevel(OA, c("Low", "High")), 
                                        y=Survival, 
                                        colour=fct_relevel(Salinity, c("Low", "High")), 
                                        linetype = Temp)) +
                                          geom_boxplot() + 
                                          theme_classic() +  
                                          geom_jitter(position = position_dodge2(width = 0.75))+
                                         # ylim(0.2,0.6) +
                                          stat_summary(fun.y="mean",position = position_dodge2(width = 0.75)) +
                                          theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank())+ 
                                          theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))+
                                          labs(title="Age = 8 days (high temp only)", 
                                               x ="pCO2 level", 
                                               y = expression(Respiration~rate~"("~ng~L^{-1}~O[2]%.%indiv^{-1}%.% hr^{-1}~")")) + 
                                          theme(axis.title.y = element_text(size = rel(1.3), angle =90), 
                                                axis.title.x = element_text(size = rel(1.3), angle = 0)) +
                                          theme(axis.text=element_text(size=12)) 

setwd("C:/Users/samjg/Documents/Github_repositories/Cvirginica_multistressor/RAnalysis")
pdf("Output/Length_Survival/Survival_age_8days_hightemp.pdf", width=8, height=6)
print(Age8_Survival_Boxplot)
dev.off()


```


### Age 11 days ALL DATA  ------------

```{r, SURVIVAL Age 11 days - all data}
age_11<- Av_length.survival_dat%>%
  filter(Day=="11") %>% 
  arrange(Survival) %>% 
  mutate(Survival = ifelse(Survival == last(Survival), 0.75, Survival)) # ID #12 was 0.116 -  whereas survival on day 11 was 0.75 - this is an artifact of increased numbers? I changed to 0.75 to reflect no losses between days 11 and 11


# Age 11 Length mod - all data -------------------------------------------------------------------------------------- #


Age11_Survival_lme_mod <- lme(Survival~OA*Salinity*Temp,random=~1|random_fact,data=age_11)
pander(anova(Age11_Survival_lme_mod), style='rmarkdown') # anova table of lm
# |        &nbsp;        | numDF | denDF | F-value |  p-value  |
# |:--------------------:|:-----:|:-----:|:-------:|:---------:|
# |   **(Intercept)**    |   1   |  16   |  29.69  | 5.353e-05 |
# |        **OA**        |   1   |  16   |  1.068  |  0.3167   |
# |     **Salinity**     |   1   |  16   |  9.248  | 0.007782  |
# |       **Temp**       |   1   |  16   |  1.072  |   0.316   |
# |   **OA:Salinity**    |   1   |  16   | 0.07552 |   0.787   |
# |     **OA:Temp**      |   1   |  16   | 0.3669  |  0.5532   |
# |  **Salinity:Temp**   |   1   |  16   |  0.386  |  0.5431   |
# | **OA:Salinity:Temp** |   1   |  16   | 0.6535  |  0.4307   |
# | **OA:Salinity:Temp** |   1   |  16   | 0.2301  |   0.638   |
leveneTest(residuals(Age11_Survival_lme_mod) ~ age_11$Temp*age_11$OA*age_11$Salinity) # 0.2159 pass
boxplot(residuals(Age11_Survival_lme_mod) ~ age_11$Temp*age_11$OA*age_11$Salinity) # visual of residuals grouped
qqnorm(resid(Age11_Survival_lme_mod)) # check for normality of residuals - looks okay


# run mod (lm model) 
Age11_Survival_lm_mod <- lm(Survival~OA*Salinity*Temp,data=age_11)
pander(anova(Age11_Survival_lm_mod), style='rmarkdown') # anova table of lm
# |        &nbsp;        | Df |  Sum Sq  | Mean Sq  | F value |  Pr(>F)  |
# |:--------------------:|:--:|:--------:|:--------:|:-------:|:--------:|
# |        **OA**        | 1  | 0.02429  | 0.02429  |  1.068  |  0.3167  |
# |     **Salinity**     | 1  |  0.2103  |  0.2103  |  9.248  | 0.007782 |
# |       **Temp**       | 1  | 0.02436  | 0.02436  |  1.072  |  0.316   |
# |   **OA:Salinity**    | 1  | 0.001717 | 0.001717 | 0.07552 |  0.787   |
# |     **OA:Temp**      | 1  | 0.008341 | 0.008341 | 0.3669  |  0.5532  |
# |  **Salinity:Temp**   | 1  | 0.008777 | 0.008777 |  0.386  |  0.5431  |
# | **OA:Salinity:Temp** | 1  | 0.01486  | 0.01486  | 0.6535  |  0.4307  |
# |    **Residuals**     | 16 |  0.3638  | 0.02274  |   NA    |    NA    |
library(stats)
shapiro.test(residuals(Age11_Survival_lm_mod)) # 0.008833 pass
leveneTest(residuals(Age11_Survival_lm_mod) ~ age_11$Temp*age_11$OA*age_11$Salinity) # 0.2159 pass
boxplot(residuals(Age11_Survival_lm_mod) ~ age_11$Temp*age_11$OA*age_11$Salinity) # visual of residuals grouped
qqnorm(resid(Age11_Survival_lm_mod)) # check for normality of residuals - looks okay





# post hoc tests --------------------------------------------------------------------------------------------------- #

posthoc<-emmeans(Age11_Survival_lm_mod, pairwise~Salinity, adjust="tukey")

multcomp::cld(posthoc$emmeans,alpha = 0.5, Letters = letters)
# Salinity emmean     SE df lower.CL upper.CL .group
#  Low      0.0741 0.0435 16  -0.0182    0.166  a    
#  High     0.2613 0.0435 16   0.1690    0.354   b   
#72% higher under high salinity

# plot the data  ----------------------------------------------------------------------------------------------------- #
Age11_Survival_Boxplot_2 <- age_11 %>% 
  dplyr::group_by(OA,Salinity, Temp) %>% 
  dplyr::summarise(mean_surv = mean(Survival), 
                   n         = n(),
                   sd_surv   = sd(Survival),
                   se_surv   = sd_surv/(sqrt(n))) %>% 
                              ggplot(aes(x=fct_relevel(OA, c("Low", "High")), 
                                                             y=mean_surv, 
                                                             colour=fct_relevel(Salinity, c("Low", "High")), 
                                                             linetype = Temp)) +
                              geom_point(aes (fill = fct_relevel(Salinity, c("Low", "High")), shape = Temp), position = "dodge2") +
                              geom_errorbar(aes(ymin = mean_surv - se_surv, ymax = mean_surv + se_surv), width = 0.5, position= "dodge2") +
                              theme_classic() +  
                              #ylim(0,0.75) +
                              theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank())+ 
                              theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))+
                              labs(title="Age = 11 days", x ="pCO2 level", y = "Survival")+ 
                              theme(axis.title.y = element_text(size = rel(1.3), angle =90), axis.title.x = element_text(size = rel(1.3), angle = 0))+
                              theme(axis.text=element_text(size=12)) 

setwd("C:/Users/samjg/Documents/Github_repositories/Cvirginica_multistressor/RAnalysis")
pdf("Output/Length_Survival/Survival_age_11days_MeanSE.pdf", width=11, height=6)
print(Age11_Survival_Boxplot_2)
dev.off()




##Here Low Salinity treatments are in Blue
Age11_Survival_Boxplot <-ggplot(data=age_11, aes(x=fct_relevel(OA, c("Low", "High")), 
                                        y=Survival, 
                                        colour=fct_relevel(Salinity, c("Low", "High")), 
                                        linetype = Temp)) +
                                          geom_boxplot() + 
                                          theme_classic() +  
                                          geom_jitter(position = position_dodge2(width = 0.75))+
                                          ylim(0,0.75) +
                                          stat_summary(fun.y="mean",position = position_dodge2(width = 0.75)) +
                                          theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank())+ 
                                          theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))+
                                          labs(title="Age = 11 days (all data)", 
                                               x ="pCO2 level", 
                                               y = expression(Respiration~rate~"("~ng~L^{-1}~O[2]%.%indiv^{-1}%.% hr^{-1}~")")) + 
                                          theme(axis.title.y = element_text(size = rel(1.3), angle =90), 
                                                axis.title.x = element_text(size = rel(1.3), angle = 0)) +
                                          theme(axis.text=element_text(size=12)) 

setwd("C:/Users/samjg/Documents/Github_repositories/Cvirginica_multistressor/RAnalysis")
pdf("Output/Length_Survival/Survival_age_11days.pdf", width=11, height=6)
print(Age11_Survival_Boxplot)
dev.off()

```


### Age 15 days ALL DATA  ------------

```{r, SURVIVAL Age 15 days - all data}
age_15<- Av_length.survival_dat%>%
  filter(Day=="15") %>% 
  arrange(Survival) %>% 
  mutate(Survival = ifelse(Survival == last(Survival), 0.75, Survival)) # ID #12 was 0.156 -  whereas survival on day 15 was 0.75 - this is an artifact of increased numbers? I changed to 0.75 to reflect no losses between days 15 and 15


# Age 15 Length mod - all data -------------------------------------------------------------------------------------- #


Age15_Survival_lme_mod <- lme(Survival~OA*Salinity*Temp,random=~1|random_fact,data=age_15)
pander(anova(Age15_Survival_lme_mod), style='rmarkdown') # anova table of lm
# |        &nbsp;        | numDF | denDF | F-value | p-value  |
# |:--------------------:|:-----:|:-----:|:-------:|:--------:|
# |   **(Intercept)**    |   1   |  16   |  13.17  | 0.002259 |
# |        **OA**        |   1   |  16   |  2.751  |  0.1166  |
# |     **Salinity**     |   1   |  16   |  6.994  | 0.01766  |
# |       **Temp**       |   1   |  16   | 0.4106  |  0.5307  |
# |   **OA:Salinity**    |   1   |  16   | 0.8238  |  0.3775  |
# |     **OA:Temp**      |   1   |  16   | 0.0958  |  0.7609  |
# |  **Salinity:Temp**   |   1   |  16   | 0.05448 |  0.8184  |
# | **OA:Salinity:Temp** |   1   |  16   | 0.5834  |  0.4561  |
leveneTest(residuals(Age15_Survival_lme_mod) ~ age_15$Temp*age_15$OA*age_15$Salinity) # 0.4224 pass
boxplot(residuals(Age15_Survival_lme_mod) ~ age_15$Temp*age_15$OA*age_15$Salinity) # visual of residuals grouped
qqnorm(resid(Age15_Survival_lme_mod)) # check for normality of residuals - looks okay


# run mod (lm model) 
Age15_Survival_lm_mod <- lm(Survival~OA*Salinity*Temp,data=age_15)
pander(anova(Age15_Survival_lm_mod), style='rmarkdown') # anova table of lm
# |        &nbsp;        | Df |  Sum Sq  | Mean Sq  | F value | Pr(>F)  |
# |:--------------------:|:--:|:--------:|:--------:|:-------:|:-------:|
# |        **OA**        | 1  | 0.06469  | 0.06469  |  2.751  | 0.1166  |
# |     **Salinity**     | 1  |  0.1644  |  0.1644  |  6.994  | 0.01766 |
# |       **Temp**       | 1  | 0.009654 | 0.009654 | 0.4106  | 0.5307  |
# |   **OA:Salinity**    | 1  | 0.01937  | 0.01937  | 0.8238  | 0.3775  |
# |     **OA:Temp**      | 1  | 0.002252 | 0.002252 | 0.0958  | 0.7609  |
# |  **Salinity:Temp**   | 1  | 0.001281 | 0.001281 | 0.05448 | 0.8184  |
# | **OA:Salinity:Temp** | 1  | 0.01372  | 0.01372  | 0.5834  | 0.4561  |
# |    **Residuals**     | 16 |  0.3762  | 0.02351  |   NA    |   NA    |
library(stats)
shapiro.test(residuals(Age15_Survival_lm_mod)) # 6.513e-05 pass
leveneTest(residuals(Age15_Survival_lm_mod) ~ age_15$Temp*age_15$OA*age_15$Salinity) # 0.4224 pass
boxplot(residuals(Age15_Survival_lm_mod) ~ age_15$Temp*age_15$OA*age_15$Salinity) # visual of residuals grouped
qqnorm(resid(Age15_Survival_lm_mod)) # check for normality of residuals - looks okay





# post hoc tests --------------------------------------------------------------------------------------------------- #

posthoc<-emmeans(Age15_Survival_lm_mod, pairwise~Salinity, adjust="tukey")

multcomp::cld(posthoc$emmeans,alpha = 0.5, Letters = letters)

 # Salinity emmean     SE df lower.CL upper.CL .group
 # Low      0.0308 0.0443 16   -0.063    0.125  a    
 # High     0.1963 0.0443 16    0.103    0.290   b  
#36.1% higher under high salinity

# plot the data  ----------------------------------------------------------------------------------------------------- #
Age15_Survival_Boxplot_2 <- age_15 %>% 
  dplyr::group_by(OA,Salinity, Temp) %>% 
  dplyr::summarise(mean_surv = mean(Survival), 
                   n         = n(),
                   sd_surv   = sd(Survival),
                   se_surv   = sd_surv/(sqrt(n))) %>% 
                              ggplot(aes(x=fct_relevel(OA, c("Low", "High")), 
                                                             y=mean_surv, 
                                                             colour=fct_relevel(Salinity, c("Low", "High")), 
                                                             linetype = Temp)) +
                              geom_point(aes (fill = fct_relevel(Salinity, c("Low", "High")), shape = Temp), position = "dodge2") +
                              geom_errorbar(aes(ymin = mean_surv - se_surv, ymax = mean_surv + se_surv), width = 0.5, position= "dodge2") +
                              theme_classic() +  
                              #ylim(0,0.75) +
                              theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank())+ 
                              theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))+
                              labs(title="Age = 15 days", x ="pCO2 level", y = "Survival")+ 
                              theme(axis.title.y = element_text(size = rel(1.3), angle =90), axis.title.x = element_text(size = rel(1.3), angle = 0))+
                              theme(axis.text=element_text(size=12)) 

setwd("C:/Users/samjg/Documents/Github_repositories/Cvirginica_multistressor/RAnalysis")
pdf("Output/Length_Survival/Survival_age_15days_MeanSE.pdf", width=15, height=6)
print(Age15_Survival_Boxplot_2)
dev.off()




##Here Low Salinity treatments are in Blue
Age15_Survival_Boxplot <-ggplot(data=age_15, aes(x=fct_relevel(OA, c("Low", "High")), 
                                        y=Survival, 
                                        colour=fct_relevel(Salinity, c("Low", "High")), 
                                        linetype = Temp)) +
                                          geom_boxplot() + 
                                          theme_classic() +  
                                          geom_jitter(position = position_dodge2(width = 0.75))+
                                          ylim(0,0.75) +
                                          stat_summary(fun.y="mean",position = position_dodge2(width = 0.75)) +
                                          theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank())+ 
                                          theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))+
                                          labs(title="Age = 15 days (all data)", 
                                               x ="pCO2 level", 
                                               y = expression(Respiration~rate~"("~ng~L^{-1}~O[2]%.%indiv^{-1}%.% hr^{-1}~")")) + 
                                          theme(axis.title.y = element_text(size = rel(1.3), angle =90), 
                                                axis.title.x = element_text(size = rel(1.3), angle = 0)) +
                                          theme(axis.text=element_text(size=12)) 

setwd("C:/Users/samjg/Documents/Github_repositories/Cvirginica_multistressor/RAnalysis")
pdf("Output/Length_Survival/Survival_age_15days.pdf", width=15, height=6)
print(Age15_Survival_Boxplot)
dev.off()

```
