---
title: "Cvirginica experiment: Seawater Chemistry"
author: "Samuel Gurr"
date: "9/22/2021"
output: html_document
---

```{r setup, include=FALSE}
# Purpose: Oyster project 2021 - Respiration rate data 
# analysis of respiration rate data
# Written by: Sam J Gurr (last edit 9/14/2021)

# LOAD PACKAGES :::::::::::::::::::::::::::::::::::::::::::::::::::::::
library(dplyr)
library(ggplot2)
library(reshape2)
library(qwraps2)
library(knitr)
library(kableExtra)
library(car)
library(agricolae) # tukey letters
# SET WORKING DIRECTORY :::::::::::::::::::::::::::::::::::::::::::::::
setwd("C:/Users/samjg/Documents/Github_repositories/Cvirginica_multistressor/RAnalysis") # personal computer
# setwd("C:/Users/samuel.gurr/Documents/Github_repositories/Cvriginica_multistressor/RAnalysis") # Work computer

# LOAD DATA :::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
# chem <- read.csv(file="Data/Water_chem/Chem_logsheet_raw.csv", header=TRUE) # load the chem data
chem <- read.csv(file="Data/Water_chem/cumulative_raw/Seawater_chem_raw.csv", header=TRUE) # load the chem data
names(chem)<-gsub("\\..","_",names(chem)) # insert underscore sin the column names to ease reading the columns 
# View(chem) # view the file
```


# PLOTS AND ANALYSIS - Aragonite saturation levels

```{r}
# Objective: Aragonite saturation state ties together the high vs. low full reciprocal Temp x OA x salinity challenge 
# in which two major factors (1) low salinity and (2) high pCO2 drive differences in aragoinite saturation state 
# interestingly it appears there are 4 groups 
# (1) low aragoinite as low sal+high pCO2
# (2)  high aragonite as high salinity low pCO2
# (3a) mid aragonite driven by low slainity (and low pCO2)
# (3b) mid aragonite driven by high pCO2 (under high salinity)

# in this chunk... 
# I will plot and statistically examine differences in aragonite saturation state for all 8 groups and in the consolidated 4 described above 


# NOTe: full carbonate chemistry was taken non-continuosly, call all rows that contain full carb


#  CONSOLIDATE TARGET DATA, NAME NEW COLUMNS 
names(chem)
chem.aragonite <- chem %>% 
  tidyr::drop_na(WAr_out) %>% # omit rows with NA for aragonite sat state
  dplyr::select(c('Date','Chamber_.','Temp','pCO2','Sal','WAr_out')) %>% 
  dplyr::mutate(all_treat = paste(Temp,pCO2, Sal, sep = '_')) %>% 
  dplyr::mutate(OAxSal = paste(pCO2, Sal, sep = '_')) 


unique(chem.aragonite$Date) # "4/29/2021" "5/3/2021"  "5/7/2021"  "5/10/2021" "5/14/2021" "5/17/2021"

# Means within date (consolidate replicates within date to single value)

alltreat.Date.MEANS <- chem.aragonite %>% 
  dplyr::group_by(Date, all_treat,Temp,pCO2,Sal) %>% 
  dplyr::summarise(mean_AragoniteSat.date  = mean(WAr_out), 
                    n                 = n(),
                    sd_AragoniteSat.date   = sd(WAr_out),
                    se_AragoniteSat.date   = sd_AragoniteSat.date/(sqrt(n))) 

all.mod <- aov(log(mean_AragoniteSat.date) ~  all_treat, data= alltreat.Date.MEANS) # outlier [-35,]
shapiro.test(resid(all.mod)) # 0.04996  normal
leveneTest(all.mod) # 0.4938 pass
qqnorm(resid(all.mod)) # view qqnrom
hist(resid(all.mod)) # view histogram
summary(all.mod) # summary printed below...
#             Df Sum Sq Mean Sq F value Pr(>F)    
# all_treat    7 20.365  2.9093    1017 <2e-16 ***
# Residuals   40  0.114  0.0029 

# posthoc
allmod.means   <- emmeans::emmeans(object = all.mod, pairwise ~ "all_treat", adjust = "tukey")
allmod.letters <- HSD.test(all.mod, "all_treat", group=TRUE)
#      log(mean_AragoniteSat.date) groups
# H_L_H                   0.5599737      a
# L_L_H                   0.4108005      b
# H_H_H                  -0.2443737      c
# H_L_L                  -0.4024329      d interesting
# L_H_H                  -0.4141954      d interesting - the mid treatments driven by differing factors
# L_L_L                  -0.6065619      e
# H_H_L                  -1.2120345      f
# L_H_L                  -1.4448603      g
library(forcats)


AragonitePlot <- alltreat.Date.MEANS %>% 
      dplyr::mutate(Temp = substr(all_treat, 1,1)) %>%
      dplyr::mutate(pCO2 = substr(all_treat, 3,3)) %>%
      dplyr::mutate(Sal = substr(all_treat, 5,5)) %>%
      dplyr::mutate(pCO2xSal = paste(pCO2, Sal, sep = '_')) %>% 
      dplyr::mutate(pCO2xSal = fct_reorder(pCO2xSal, mean_AragoniteSat.date)) %>%  # reorder for x axis
      dplyr::mutate(Temp = fct_relevel(Temp, "L", "H")) %>% 
        ggplot(aes(pCO2xSal , mean_AragoniteSat.date, grfill = Temp)) +
        theme(panel.grid=element_blank()) +
        geom_boxplot(size=0.2, alpha=0.1) +
        scale_fill_manual(values=c("grey50", "white")) +
        geom_point(aes(fill=Temp), 
                   shape = 21, 
                   size = 2, 
                   position = position_jitterdodge(jitter.width = 0.1)) +
        theme_classic() +
        theme(axis.text=element_text(size=12),
              axis.title=element_text(size=12)) +
        stat_summary(fun.y=mean, 
                     geom="point", 
                     shape=18, 
                     size=4, 
                     color="black", 
                     fill="white")

setwd("C:/Users/samjg/Documents/Github_repositories/Cvirginica_multistressor/RAnalysis/Output/Water_Chem/")
pdf("plots/AragoniteSaturation_meansbydate.pdf", width=8, height=8)
print(AragonitePlot)
dev.off()




```

# TABLE 

```{r use dplyr to build chemistry table, include=FALSE}


# NOTe: full carbonate chemistry was taken non-continuosly, call all rows that contain full carb
carbchem.MASTER         <- chem[!(is.na(chem$WAr_out)),]
colnames(carbchem.MASTER)
# change to long format to properly facet
carbchem.MASTER_long <- carbchem.MASTER %>% 
  dplyr::select(!c(Chamber_.,
                   pH_Green_urple,
                   Total_P_mmol_gSW,
                   t_oC_spec,
                   P__dbars,
                   P_dbars,
                   Si_Alk_out_mmol_gSW,
                   Total_Si_mmol_gSW,
                   B_Alk_out_mmol_gSW,
                   P_Alk_out_mmol_gSW,
                   Revelle_out,
                   TCO2__mmol_gSW__corrected_with_the_CRM_from_preserved_samples,
                   xCO2_ut_dry_t1atm_ppm)) %>% 
  melt(id.vars=c('Date', 'Temp', 'pCO2', 'Sal'))


# get the mean. sd. and se for all the data (not by life history!)
carbchem.MASTER_longMEANS <- carbchem.MASTER_long %>% # calc means and standard error
   na.omit() %>% 
   dplyr::group_by(Temp, pCO2, Sal, variable) %>% 
   dplyr::summarise(mean = mean(value),
                    sd   = sd(value),
                    se   = sd/(sqrt(n())) ,
                    n = n())



carbchem.MASTER_wideMEANS <- dcast(carbchem.MASTER_longMEANS, Temp + pCO2 + Sal ~ variable, value.var="mean")
carbchem.MASTER_wideStErr <- dcast(carbchem.MASTER_longMEANS, Temp + pCO2 + Sal ~ variable, value.var="se")
carbchem.MASTER_wideN     <- dcast(carbchem.MASTER_longMEANS, Temp + pCO2 + Sal ~ variable, value.var="n")

colnames(carbchem.MASTER_wideMEANS)

# final table


FINAL_TABLE                <- data.frame(matrix(nrow = nrow(carbchem.MASTER_wideMEANS), ncol = 1))

FINAL_TABLE$sal            <- carbchem.MASTER_wideMEANS$Sal

FINAL_TABLE$OA             <- carbchem.MASTER_wideMEANS$pCO2

FINAL_TABLE$temp           <- carbchem.MASTER_wideMEANS$Temp

FINAL_TABLE$Salinity       <-  paste( (paste( (signif(carbchem.MASTER_wideMEANS$Salinity, digits=3)),
                                     (signif(carbchem.MASTER_wideStErr$Salinity, digits=3)), sep=" ± ")),
                                     " (",
                                     carbchem.MASTER_wideN$Salinity,
                                     ")",
                                     sep = "")

FINAL_TABLE$pCO2           <-  paste( (paste( (signif(carbchem.MASTER_wideMEANS$pCO2_out_matm, digits=3)),
                                     (signif(carbchem.MASTER_wideStErr$pCO2_out_matm, digits=3)), sep=" ± ")),
                                     " (",
                                     carbchem.MASTER_wideN$pCO2_out_matm,
                                     ")",
                                     sep = "")

FINAL_TABLE$Temperature    <- paste( (paste( (signif(carbchem.MASTER_wideMEANS$t_oC__treatment, digits=3)),
                                     (signif(carbchem.MASTER_wideStErr$t_oC__treatment, digits=3)), sep=" ± ")),
                                     " (",
                                     carbchem.MASTER_wideN$t_oC__treatment,
                                     ")",
                                     sep = "")

FINAL_TABLE$pH             <- paste( (paste( (signif(carbchem.MASTER_wideMEANS$pH_out_chamber, digits=3)),
                                     (signif(carbchem.MASTER_wideStErr$pH_out_chamber, digits=3)), sep=" ± ")),
                                     " (",
                                     carbchem.MASTER_wideN$pH_out_chamber,
                                     ")",
                                     sep = "")

FINAL_TABLE$HCO3           <-  paste( (paste( (signif(carbchem.MASTER_wideMEANS$HCO3_out_mmol_gSW, digits=3)),
                                     (signif(carbchem.MASTER_wideStErr$HCO3_out_mmol_gSW, digits=3)), sep=" ± ")),
                                     " (",
                                     carbchem.MASTER_wideN$HCO3_out_mmol_gSW,
                                     ")",
                                     sep = "")

FINAL_TABLE$CO3           <-  paste( (paste( (signif(carbchem.MASTER_wideMEANS$CO3_out_mmol_gSW, digits=3)),
                                             "±",
                                     (signif(carbchem.MASTER_wideStErr$CO3_out_mmol_gSW, digits=3)), sep="  ")),
                                     " (",
                                     carbchem.MASTER_wideN$CO3_out_mmol_gSW,
                                     ")",
                                     sep = "")

FINAL_TABLE$TA             <- paste( (paste( (signif(carbchem.MASTER_wideMEANS$TA__mmol_gSW__Corrected_with_the_CRM, digits=3)),
                                     (signif(carbchem.MASTER_wideStErr$TA__mmol_gSW__Corrected_with_the_CRM, digits=3)), sep=" ± ")),
                                     " (",
                                     carbchem.MASTER_wideN$TA__mmol_gSW__Corrected_with_the_CRM,
                                     ")",
                                     sep = "")

FINAL_TABLE$Aragonite.Sat  <-  paste( (paste( (signif(carbchem.MASTER_wideMEANS$WAr_out, digits=3)),
                                     (signif(carbchem.MASTER_wideStErr$WAr_out, digits=3)), sep=" ± ")),
                                     " (",
                                     carbchem.MASTER_wideN$WAr_out,
                                     ")",
                                     sep = "")

# FINAL_TABLE$Calcite.Sat    <-  paste( (paste( (signif(carbchem.MASTER_wideMEANS$WCa_out, digits=3)),
#                                      (signif(carbchem.MASTER_wideStErr$WCa_out, digits=2)), sep=" ± ")),
#                                      " (",
#                                      carbchem.MASTER_wideN$WCa_out,
#                                      ")",
#                                      sep = "")

FINAL_TABLE                <- FINAL_TABLE[,-1] # view table
```


## knitR to print the table 
```{r lable output, echo=TRUE}
FINAL_TABLE %>%
  kbl(caption = "Table 1. Seawater chemistry") %>%
  kable_classic(full_width = T, html_font = "Cambria")
```


#### save data
```{r save tables, echo=TRUE}
# save output table
write.table(carbchem.MASTER_longMEANS,"C:/Users/samjg/Documents/Github_repositories/Cvirginica_multistressor/RAnalysis/Output/Water_Chem/Chem.Table_sep.csv",sep=",", row.names=FALSE)  # write table to 
write.table(FINAL_TABLE,"C:/Users/samjg/Documents/Github_repositories/Cvirginica_multistressor/RAnalysis/Output/Water_Chem/Chem.Table.csv",sep=",", row.names=FALSE, fileEncoding = "latin1")  # write table to 

```