---
title: "Survival_analysis.Rmd"
author: "Sam Gurr"
date: "11/2/2022"
output:
  pdf_document: default
  html_document: default
---




# load libraries

```{r, include=FALSE}
library(ggplot2)
library(dplyr)
library(tidyverse)
# library(multcompView)
# library(agricolae)
library(dplyr)
library(lme4)
library(ggplot2)
library(nlme)
library(car)
library(performance)
# library(stargazer)
library(emmeans)
library(pander)
# library(survminer)
library(survival)
# library(adjustedCurves)
# library(riskRegression)
# library(pammtools)
# library(bestNormalize)
```


# Set Path & load data

```{r setup}

setwd("C:/Users/samjg/Documents/Github_repositories/Cvirginica_multistressor/RAnalysis")

# survival data
Survival_dat <- read.csv("Data/Survival/Survival_master.csv", header = T) %>% 
                            dplyr::mutate(random_fact = paste( substr(Temp,1,1), 
                                                               substr(OA,1,1), 
                                                               substr(Salinity,1,1), '_', Replicate, sep = ''))
# head(Av_length.survival_dat) # view first few lines
```


# prep data 

```{r, prep the raw data for stats} 
# extract the experiment data with corresponding sample Ids from the averaged data master file...
Exp_data <-  Survival_dat %>% 
                filter(Day %in% 1) %>% 
                dplyr::select(c('Temp','OA','Salinity','Replicate','Id.', 'pH', 'AR')) %>% 
                dplyr::rename(Sample.ID = Id., Aragonite_saturation = AR)

```
 
 
 
 Plot all data
 
 
```{r survival to hatch - trochs day 1} 
 
# FILTER DATA FOR DAY 1
Survival_means_day1 <- Survival_dat %>% 
                                dplyr::filter(Day == 1) %>% 
                                na.omit() %>% 
                                dplyr::group_by(Day, OA, Salinity, Temp) %>% 
                                dplyr::summarise(mean_survival = mean(Survival), 
                                                 n           = n(),
                                                 sd_survival   = sd(Survival),
                                                 se_survival   = sd_survival/(sqrt(n))) %>%  
                                dplyr::mutate(Survival_to_hatch = (mean_survival) *100 ) %>% 
                                dplyr::mutate(OA_Sal = paste(substr(OA,1,1),
                                              substr(Salinity,1,1),
                                                  sep = ''))


# PLOT

Heatplot <- Survival_means_day1 %>% 
       ggplot(aes(x = Day,
                  y = mean_survival)) + 
       geom_rect(aes(fill = Survival_to_hatch), 
                   xmin = -Inf, 
                   xmax = Inf, 
                   ymin = -Inf, 
                   ymax = Inf, 
                   alpha = 0.3) +
      geom_point(color = 'black') +
      geom_line(aes(x = Day,
                    y = mean_survival)) +
      geom_errorbar(aes(ymin = mean_survival - se_survival, 
                        ymax = mean_survival + se_survival), 
                        width = 0.5, 
                        position= "dodge2") +
      geom_smooth(method = "lm", 
                  se = FALSE, 
                  size = 1, 
                  color = 'white') +
      theme_bw() +  
      theme(panel.grid.major = element_blank(),
            panel.grid.minor = element_blank()) +
      facet_grid(vars(Temp), 
                 vars(fct_relevel(OA_Sal, c("HL", "LL", "HH", "LH")))) +
      geom_text(size = 2, 
                   aes(x = 0.5, 
                       y = 0.8, 
                       label = paste0(round(Survival_to_hatch,2),"% survival to hatch"))) +
      scale_fill_gradient(low = "orange", 
                           high = "forestgreen", 
                           aesthetics = "fill")
setwd("C:/Users/samjg/Documents/Github_repositories/Cvirginica_multistressor/RAnalysis")
pdf("Output/Survival/plots/Survival_hatch_facetted.pdf", width=11, height=5)
print(Heatplot)
dev.off()






Survival_all_MeanSE_plot_Day1 <- Survival_means_day1 %>% 
                                  dplyr::mutate(AllTreat = as.factor(paste(OA, Salinity, Temp, sep = '_'))) %>% 
                                  ggplot(aes(x = as.numeric(Day),
                                             y = mean_survival, 
                                             group = AllTreat,
                                             colour=fct_relevel(Salinity, c("Low", "High")), 
                                             linetype = Temp)) +
                                  geom_point(aes(colour = fct_relevel(Salinity, c("Low", "High")), 
                                             shape = fct_relevel(OA, c("Low", "High"))),
                                             width = 0.5,
                                             position = "dodge2") +
                                  geom_line(aes(x = as.numeric(Day),
                                             y=mean_survival, 
                                             colour=fct_relevel(Salinity, c("Low", "High")), 
                                             linetype = Temp)) +
                                  geom_errorbar(aes(ymin = mean_survival - se_survival, 
                                                    ymax = mean_survival + se_survival), 
                                                width = 0.5, position= "dodge2") +
                                  theme_classic() +  
                                  facet_wrap(~(fct_relevel(OA, c("Low", "High"))))

```
 
```{r survival to set - days 4 to 15} 

# plot - Survival  after day 1

Survival_means <- Survival_dat %>% 
                          dplyr::filter(Day >1) %>% 
                          #na.omit() %>% 
                          dplyr::group_by(Day, OA, Salinity, Temp) %>% 
                          dplyr::summarise(mean_survival = mean(Survival), 
                                           n           = n(),
                                           sd_survival   = sd(Survival),
                                           se_survival   = sd_survival/(sqrt(n)))



Survival_to_set_means <- as.data.frame(Survival_means %>% 
  filter(Day %in% 15) %>% 
  dplyr::select(c(Day, OA, Salinity, Temp, mean_survival)) %>% 
  dplyr::group_by(OA, Salinity, Temp)  %>% 
  tidyr::spread(Day, mean_survival) %>%  # new columns titled 1 and 15 for he Age and with values for the 
  # length data grouped by treatment 
  dplyr::mutate(Survival_to_set = (`15`) *100 ) %>% 
  dplyr::select(!`15`)) 

Survival_means_MASTER <- merge(Survival_means, Survival_to_set_means, by=c('OA', 'Salinity', 'Temp')) %>% 
                              dplyr::mutate(OA_Sal = paste(substr(OA,1,1),
                                              substr(Salinity,1,1),
                                                  sep = ''))

# plot - length

Heatplot <- Survival_means_MASTER %>% 
       ggplot(aes(x = Day,
                  y = mean_survival)) + 
       geom_rect(aes(fill = Survival_to_set), 
                   xmin = -Inf, 
                   xmax = Inf, 
                   ymin = -Inf, 
                   ymax = Inf, 
                   alpha = 0.3) +
      geom_point(color = 'black') +
      geom_line(aes(x = Day,
                    y = mean_survival)) +
      geom_errorbar(aes(ymin = mean_survival - se_survival, 
                        ymax = mean_survival + se_survival), 
                        width = 0.5, 
                        position= "dodge2") +
      geom_smooth(method = "lm", 
                  se = FALSE, 
                  size = 1, 
                  color = 'white') +
      theme_bw() +  
      theme(panel.grid.major = element_blank(),
            panel.grid.minor = element_blank()) +
      facet_grid(vars(Temp), 
                 vars(fct_relevel(OA_Sal, c("HL", "LL", "HH", "LH")))) +
      geom_text(size = 2, 
                   aes(x = 12, 
                       y = 0.8, 
                       label = paste0(round(Survival_to_set,2),"% survival to set"))) +
      scale_fill_gradient(low = "orange", 
                           high = "forestgreen", 
                           aesthetics = "fill")
setwd("C:/Users/samjg/Documents/Github_repositories/Cvirginica_multistressor/RAnalysis")
pdf("Output/Survival/plots/Survival_all_facetted.pdf", width=11, height=5)
print(Heatplot)
dev.off()


Survival_all_MeanSE_plot <- Survival_means %>% 
                                dplyr::mutate(AllTreat = as.factor(paste(OA, Salinity, Temp, sep = '_'))) %>% 
                                ggplot(aes(x = as.numeric(Day),
                                           y = mean_survival, 
                                           group = AllTreat,
                                           colour=fct_relevel(Salinity, c("Low", "High")), 
                                           linetype = Temp)) +
                                geom_point(aes(colour = fct_relevel(Salinity, c("Low", "High")), 
                                           shape = fct_relevel(OA, c("Low", "High"))),
                                           width = 0.5,
                                           position = "dodge2") +
                                geom_line(aes(x = as.numeric(Day),
                                           y=mean_survival, 
                                           colour=fct_relevel(Salinity, c("Low", "High")), 
                                           linetype = Temp)) +
                                geom_errorbar(aes(ymin = mean_survival - se_survival, 
                                                  ymax = mean_survival + se_survival), 
                                              width = 0.5, position= "dodge2") +
                                theme_minimal() +  
                                stat_summary(geom="ribbon", fun.data=mean_cl_normal, width=0.1, conf.int=0.95, fill="lightblue")+
                                facet_wrap(~(fct_relevel(OA, c("Low", "High"))))
Survival_all_MeanSE_plot # view the plot
setwd("C:/Users/samjg/Documents/Github_repositories/Cvirginica_multistressor/RAnalysis")
pdf("Output/Survival/Survival_all_MeanSE.pdf", width=11, height=6)
print(Survival_all_MeanSE_plot)
dev.off()
```



:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
# Survival STATS ::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::  :::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::


### Age 24 hours ALL DATA ------------

```{r SURVIVAL Age 24 hours - all data}
age_1<- Av_length.survival_dat %>%
          filter(Day=="1")


# Age 1 Length mod - all data -------------------------------------------------------------------------------------- #


Age1_Survival_lme_mod <- lme(Survival~OA*Salinity*Temp,random=~1|random_fact,data=age_1)
pander(anova(Age1_Survival_lme_mod), style='rmarkdown') # anova table of lmer
# |        &nbsp;        | numDF | denDF | F-value |  p-value  |
# |:--------------------:|:-----:|:-----:|:-------:|:---------:|
# |   **(Intercept)**    |   1   |  16   |  1835   |     0     |
# |        **OA**        |   1   |  16   |  10.28  | 0.005513  | *
# |     **Salinity**     |   1   |  16   |  1.647  |  0.2176   |
# |       **Temp**       |   1   |  16   |  22.72  | 0.0002102 | *
# |   **OA:Salinity**    |   1   |  16   |  7.528  |  0.01442  | *
# |     **OA:Temp**      |   1   |  16   |  2.487  |  0.1344   |
# |  **Salinity:Temp**   |   1   |  16   |  2.07   |  0.1695   |
# | **OA:Salinity:Temp** |   1   |  16   |  3.096  |  0.09758  |
leveneTest(residuals(Age1_Survival_lme_mod) ~ age_1$Temp*age_1$OA*age_1$Salinity) # 0.8279- pass
boxplot(residuals(Age1_Survival_lme_mod) ~ age_1$Temp*age_1$OA*age_1$Salinity) # visual of residuals grouped
qqnorm(resid(Age1_Survival_lme_mod)) # check for normality of residuals - looks okay





Age1_Survival_lm_mod <- lm(Survival~OA*Salinity*Temp,data=age_1)
pander(anova(Age1_Survival_lm_mod), style='rmarkdown') # anova table of lmr
# |        &nbsp;        | Df |  Sum Sq  | Mean Sq  | F value |  Pr(>F)   |
# |:--------------------:|:--:|:--------:|:--------:|:-------:|:---------:|
# |        **OA**        | 1  | 0.02837  | 0.02837  |  10.28  | 0.005513  |
# |     **Salinity**     | 1  | 0.004548 | 0.004548 |  1.647  |  0.2176   |
# |       **Temp**       | 1  | 0.06273  | 0.06273  |  22.72  | 0.0002102 |
# |   **OA:Salinity**    | 1  | 0.02079  | 0.02079  |  7.528  |  0.01442  |
# |     **OA:Temp**      | 1  | 0.006866 | 0.006866 |  2.487  |  0.1344   |
# |  **Salinity:Temp**   | 1  | 0.005716 | 0.005716 |  2.07   |  0.1695   |
# | **OA:Salinity:Temp** | 1  | 0.008549 | 0.008549 |  3.096  |  0.09758  |
# |    **Residuals**     | 16 | 0.04418  | 0.002761 |   NA    |    NA     |
shapiro.test(residuals(Age1_Survival_lm_mod)) #0.156
leveneTest(residuals(Age1_Survival_lm_mod) ~ age_1$Temp*age_1$OA*age_1$Salinity) # 0.8279- pass
boxplot(residuals(Age1_Survival_lm_mod) ~ age_1$Temp*age_1$OA*age_1$Salinity) # visual of residuals grouped
qqnorm(resid(Age1_Survival_lm_mod)) # check for normality of residuals - looks okay




# post hoc tests --------------------------------------------------------------------------------------------------- #
posthoc<-emmeans(Age1_Survival_lme_mod, pairwise~OA:Salinity, adjust="tukey")
multcomp::cld(posthoc$emmeans,alpha = 0.5, Letters = letters)
#  OA   Salinity emmean     SE df lower.CL upper.CL .group
#  High Low       0.382 0.0215 16    0.336    0.427  a    
#  High High      0.468 0.0215 16    0.423    0.514   b   
#  Low  High      0.478 0.0215 16    0.433    0.524   b   
#  Low  Low       0.509 0.0215 16    0.464    0.555   b 



# plot the data  ----------------------------------------------------------------------------------------------------- #
Age1_Survival_Boxplot_2 <- age_1 %>% 
  dplyr::group_by(OA,Salinity, Temp) %>% 
  dplyr::summarise(mean_surv = mean(Survival), 
                   n         = n(),
                   sd_surv   = sd(Survival),
                   se_surv   = sd_surv/(sqrt(n))) %>% 
                              ggplot(aes(x=fct_relevel(OA, c("Low", "High")), 
                                                             y=mean_surv, 
                                                             colour=fct_relevel(Salinity, c("Low", "High")), 
                                                             linetype = Temp)) +
                              geom_point(aes (fill = fct_relevel(Salinity, c("Low", "High")), shape = Temp), position = "dodge2") +
                              geom_errorbar(aes(ymin = mean_surv - se_surv, 
                                                ymax = mean_surv + se_surv,
                                                fill = fct_relevel(Salinity, c("Low", "High"))), 
                                                width = 0.5, position= "dodge2") +
                              theme_classic() +  
                              ylim(0.2,0.6) +
                              theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank())+ 
                              theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))+
                              labs(title="Age = 24 hours", x ="pCO2 level", y = "Survival")+ 
                              theme(axis.title.y = element_text(size = rel(1.3), angle =90), axis.title.x = element_text(size = rel(1.3), angle = 0))+
                              theme(axis.text=element_text(size=12)) 

setwd("C:/Users/samjg/Documents/Github_repositories/Cvirginica_multistressor/RAnalysis")
pdf("Output/Survival/Survival_age_24hrs_MeanSE.pdf", width=8, height=6)
print(Age1_Survival_Boxplot_2)
dev.off()

Age1_Survival_Boxplot <-ggplot(data=age_1, aes(x=fct_relevel(OA, c("Low", "High")), 
                                        y=Survival, 
                                        colour=fct_relevel(Salinity, c("Low", "High")), 
                                        linetype = Temp)) +
                                          geom_boxplot() + 
                                          theme_classic() +  
                                          geom_jitter(position = position_dodge2(width = 0.75))+                                         # ylim(0.2,0.6) +
                                          stat_summary(fun.y="mean",position = position_dodge2(width = 0.75)) +
                                          theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank())+ 
                                          theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))+
                                          labs(title="Age = 24 hours (all data)", 
                                               x ="pCO2 level", 
                                               y = expression(Respiration~rate~"("~ng~L^{-1}~O[2]%.%indiv^{-1}%.% hr^{-1}~")")) + 
                                          theme(axis.title.y = element_text(size = rel(1.3), angle =90), 
                                                axis.title.x = element_text(size = rel(1.3), angle = 0)) +
                                          theme(axis.text=element_text(size=12)) 
  
setwd("C:/Users/samjg/Documents/Github_repositories/Cvirginica_multistressor/RAnalysis")
pdf("Output/Survival/Survival_age_24hrs.pdf", width=8, height=6)
print(Age1_Survival_Boxplot)
dev.off()
```


### Age 24 hours HIGH TEMP ONLY ------------

```{r, SURVIVAL Age 24 hours - HIGH TEMP ONLY}
age_1_hightemp <- Av_length.survival_dat %>%
                      filter(Day=="1") %>% 
                      dplyr::filter(Temp %in% 'High')


# Age 1 Length mod - all data -------------------------------------------------------------------------------------- #


Age1_Survival_lme_mod_hightemp <- lme(Survival~OA*Salinity,random=~1|random_fact,data=age_1_hightemp)
pander(anova(Age1_Survival_lme_mod_hightemp), style='rmarkdown') # anova table of lmer
# |     &nbsp;      | numDF | denDF | F-value |  p-value  |
# |:---------------:|:-----:|:-----:|:-------:|:---------:|
# | **(Intercept)** |   1   |   8   |  2296   | 3.977e-11 |
# |     **OA**      |   1   |   8   |  23.18  |  0.00133  | * main effect of OA 
# |  **Salinity**   |   1   |   8   | 0.02447 |  0.8796   |
# | **OA:Salinity** |   1   |   8   | 0.9816  |  0.3508   |
leveneTest(residuals(Age1_Survival_lme_mod_hightemp) ~ age_1_hightemp$OA*age_1_hightemp$Salinity) # 0.5608- pass
boxplot(residuals(Age1_Survival_lme_mod_hightemp) ~ age_1_hightemp$OA*age_1_hightemp$Salinity) # visual of residuals grouped
qqnorm(resid(Age1_Survival_lme_mod_hightemp)) # check for normality of residuals - looks okay


# lm model
Age1_Survival_lm_mod_hightemp <- lm(Survival~OA*Salinity,data=age_1_hightemp)
pander(anova(Age1_Survival_lm_mod_hightemp), style='rmarkdown') # anova table of lm
# |     &nbsp;      | Df |  Sum Sq   |  Mean Sq  | F value | Pr(>F)  |
# |:---------------:|:--:|:---------:|:---------:|:-------:|:-------:|
# |     **OA**      | 1  |  0.03158  |  0.03158  |  23.18  | 0.00133 | * main effect of OA 
# |  **Salinity**   | 1  | 3.333e-05 | 3.333e-05 | 0.02447 | 0.8796  |
# | **OA:Salinity** | 1  | 0.001337  | 0.001337  | 0.9816  | 0.3508  |
# |  **Residuals**  | 8  |  0.0109   | 0.001362  |   NA    |   NA    |
shapiro.test(residuals(Age1_Survival_lm_mod_hightemp)) # 0.7963
leveneTest(residuals(Age1_Survival_lm_mod_hightemp) ~ age_1_hightemp$OA*age_1_hightemp$Salinity) # 0.5608- pass
boxplot(residuals(Age1_Survival_lm_mod_hightemp) ~ age_1_hightemp$OA*age_1_hightemp$Salinity) # visual of residuals grouped
qqnorm(resid(Age1_Survival_lm_mod_hightemp)) # check for normality of residuals - looks okay


# post hoc tests --------------------------------------------------------------------------------------------------- #

posthoc<-lsmeans(Age1_Survival_lme_mod_hightemp, ~OA, adjust="tukey")
posthoc<-emmeans(Age1_Survival_lme_mod_hightemp, pairwise~OA, adjust="tukey")

multcomp::cld(posthoc$emmeans,alpha = 0.5, Letters = letters)
 # OA   emmean     SE df lower.CL upper.CL .group
 # High  0.459 0.0151  8    0.425    0.494  a    
 # Low   0.562 0.0151  8    0.527    0.597   b 



# plot the data  ----------------------------------------------------------------------------------------------------- #



Age1_Survival_Boxplot_2 <- age_1_hightemp %>% 
  dplyr::group_by(OA,Salinity) %>% 
  dplyr::summarise(mean_surv = mean(Survival), 
                   n         = n(),
                   sd_surv   = sd(Survival),
                   se_surv   = sd_surv/(sqrt(n))) %>% 
                              ggplot(aes(x=fct_relevel(OA, c("Low", "High")), 
                                                             y=mean_surv, 
                                                             colour=fct_relevel(Salinity, c("Low", "High"))))+
                              geom_point(aes (fill = fct_relevel(Salinity, c("Low", "High"))), position = "dodge2") +
                              geom_errorbar(aes(ymin = mean_surv - se_surv, 
                                                ymax = mean_surv + se_surv,
                                                fill = fct_relevel(Salinity, c("Low", "High"))), 
                                                width = 0.5, position= "dodge2") +
                              theme_classic() +  
                              ylim(0.2,0.6) +
                              theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank())+ 
                              theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))+
                              labs(title="Age = 24 hours", x ="pCO2 level", y = "Survival")+ 
                              theme(axis.title.y = element_text(size = rel(1.3), 
                                                                angle =90), 
                                                                axis.title.x = element_text(size = rel(1.3), 
                                                                angle = 0)) +
                              theme(axis.text=element_text(size=12)) 

setwd("C:/Users/samjg/Documents/Github_repositories/Cvirginica_multistressor/RAnalysis")
pdf("Output/Survival/Survival_age_24hrs_MeanSE_hightemp.pdf", width=8, height=6)
print(Age1_Survival_Boxplot_2)
dev.off()
 
Age1_Survival_Boxplot <-ggplot(data=age_1_hightemp, aes(x=fct_relevel(OA, c("Low", "High")), 
                                        y=Survival, 
                                        colour=fct_relevel(Salinity, c("Low", "High")), 
                                        linetype = Temp)) +
                                          geom_boxplot() + 
                                          theme_classic() +  
                                          geom_jitter(position = position_dodge2(width = 0.75))+                                         # ylim(0.2,0.6) +
                                          stat_summary(fun.y="mean",position = position_dodge2(width = 0.75)) +
                                          theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank())+ 
                                          theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))+
                                          labs(title="Age = 24 hours (all data)", 
                                               x ="pCO2 level", 
                                               y = expression(Respiration~rate~"("~ng~L^{-1}~O[2]%.%indiv^{-1}%.% hr^{-1}~")")) + 
                                          theme(axis.title.y = element_text(size = rel(1.3), angle =90), 
                                                axis.title.x = element_text(size = rel(1.3), angle = 0)) +
                                          theme(axis.text=element_text(size=12)) 
  
setwd("C:/Users/samjg/Documents/Github_repositories/Cvirginica_multistressor/RAnalysis")
pdf("Output/Survival/Survival_age_24hrs_hightemp.pdf", width=8, height=6)
print(Age1_Survival_Boxplot)
dev.off()

```



### Age 4 days ALL DATA  ------------

```{r, SURVIVAL Age 4 days - all data}
age_4<- Av_length.survival_dat%>%
  filter(Day=="4") %>% 
  arrange(Survival) %>% 
  mutate(Survival = ifelse(Survival == last(Survival), 0.75, Survival)) # ID #12 was 0.46 -  whereas survival on day 4 was 0.75 - this is an artifact of increased numbers? I changed to 0.75 to reflect no losses between days 4 and 4


# Age 4 Length mod - all data -------------------------------------------------------------------------------------- #


Age4_Survival_lme_mod <- lme(Survival~OA*Salinity*Temp,random=~1|random_fact,data=age_4)
pander(anova(Age4_Survival_lme_mod), style='rmarkdown') # anova table of lm
# |        &nbsp;        | numDF | denDF | F-value |  p-value  |
# |:--------------------:|:-----:|:-----:|:-------:|:---------:|
# |   **(Intercept)**    |   1   |  16   |  188.3  | 2.878e-10 |
# |        **OA**        |   1   |  16   |  1.342  |  0.2638   |
# |     **Salinity**     |   1   |  16   |  9.182  | 0.007963  | * 
# |       **Temp**       |   1   |  16   |  3.637  |  0.07464  | 
# |   **OA:Salinity**    |   1   |  16   | 0.5783  |   0.458   |
# |     **OA:Temp**      |   1   |  16   |  1.396  |  0.2546   |
# |  **Salinity:Temp**   |   1   |  16   | 0.06036 |   0.809   |
# | **OA:Salinity:Temp** |   1   |  16   | 0.2301  |   0.638   |
leveneTest(residuals(Age4_Survival_lme_mod) ~ age_4$Temp*age_4$OA*age_4$Salinity) # 0.712 pass
boxplot(residuals(Age4_Survival_lme_mod) ~ age_4$Temp*age_4$OA*age_4$Salinity) # visual of residuals grouped
qqnorm(resid(Age4_Survival_lme_mod)) # check for normality of residuals - looks okay


# run mod (lm model) 
Age4_Survival_lm_mod <- lm(Survival~OA*Salinity*Temp,data=age_4)
pander(anova(Age4_Survival_lm_mod), style='rmarkdown') # anova table of lm
# |        &nbsp;        | Df |  Sum Sq  | Mean Sq  | F value |  Pr(>F)  |
# |:--------------------:|:--:|:--------:|:--------:|:-------:|:--------:|
# |        **OA**        | 1  | 0.04084  | 0.04084  |  1.342  |  0.2638  |
# |     **Salinity**     | 1  |  0.2795  |  0.2795  |  9.182  | 0.007963 |
# |       **Temp**       | 1  |  0.1107  |  0.1107  |  3.637  | 0.07464  |
# |   **OA:Salinity**    | 1  |  0.0176  |  0.0176  | 0.5783  |  0.458   |
# |     **OA:Temp**      | 1  |  0.0425  |  0.0425  |  1.396  |  0.2546  |
# |  **Salinity:Temp**   | 1  | 0.001837 | 0.001837 | 0.06036 |  0.809   |
# | **OA:Salinity:Temp** | 1  | 0.007004 | 0.007004 | 0.2301  |  0.638   |
# |    **Residuals**     | 16 |  0.4871  | 0.03044  |   NA    |    NA    |
library(stats)
shapiro.test(residuals(Age4_Survival_lm_mod)) # 0.2763 pass
leveneTest(residuals(Age4_Survival_lm_mod) ~ age_4$Temp*age_4$OA*age_4$Salinity) # 0.712 pass
boxplot(residuals(Age4_Survival_lm_mod) ~ age_4$Temp*age_4$OA*age_4$Salinity) # visual of residuals grouped
qqnorm(resid(Age4_Survival_lm_mod)) # check for normality of residuals - looks okay





# post hoc tests --------------------------------------------------------------------------------------------------- #

posthoc<-emmeans(Age4_Survival_lm_mod, pairwise~Salinity, adjust="tukey")

multcomp::cld(posthoc$emmeans,alpha = 0.5, Letters = letters)
# Salinity emmean     SE df lower.CL upper.CL .group
#  Low       0.381 0.0504 16    0.274    0.488  a    
#  High      0.597 0.0504 16    0.490    0.703   b 
#36.1% higher under high salinity

# plot the data  ----------------------------------------------------------------------------------------------------- #
Age4_Survival_Boxplot_2 <- age_4 %>% 
  dplyr::group_by(OA,Salinity, Temp) %>% 
  dplyr::summarise(mean_surv = mean(Survival), 
                   n         = n(),
                   sd_surv   = sd(Survival),
                   se_surv   = sd_surv/(sqrt(n))) %>% 
                              ggplot(aes(x=fct_relevel(OA, c("Low", "High")), 
                                                             y=mean_surv, 
                                                             colour=fct_relevel(Salinity, c("Low", "High")), 
                                                             linetype = Temp)) +
                              geom_point(aes (fill = fct_relevel(Salinity, c("Low", "High")), shape = Temp), position = "dodge2") +
                              geom_errorbar(aes(ymin = mean_surv - se_surv, ymax = mean_surv + se_surv), width = 0.5, position= "dodge2") +
                              theme_classic() +  
                              #ylim(0,0.75) +
                              theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank())+ 
                              theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))+
                              labs(title="Age = 4 days", x ="pCO2 level", y = "Survival")+ 
                              theme(axis.title.y = element_text(size = rel(1.3), angle =90), axis.title.x = element_text(size = rel(1.3), angle = 0))+
                              theme(axis.text=element_text(size=12)) 

setwd("C:/Users/samjg/Documents/Github_repositories/Cvirginica_multistressor/RAnalysis")
pdf("Output/Survival/Survival_age_4days_MeanSE.pdf", width=4, height=6)
print(Age4_Survival_Boxplot_2)
dev.off()




##Here Low Salinity treatments are in Blue
Age4_Survival_Boxplot <-ggplot(data=age_4, aes(x=fct_relevel(OA, c("Low", "High")), 
                                        y=Survival, 
                                        colour=fct_relevel(Salinity, c("Low", "High")), 
                                        linetype = Temp)) +
                                          geom_boxplot() + 
                                          theme_classic() +  
                                          geom_jitter(position = position_dodge2(width = 0.75))+
                                          ylim(0,0.75) +
                                          stat_summary(fun.y="mean",position = position_dodge2(width = 0.75)) +
                                          theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank())+ 
                                          theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))+
                                          labs(title="Age = 4 days (all data)", 
                                               x ="pCO2 level", 
                                               y = expression(Respiration~rate~"("~ng~L^{-1}~O[2]%.%indiv^{-1}%.% hr^{-1}~")")) + 
                                          theme(axis.title.y = element_text(size = rel(1.3), angle =90), 
                                                axis.title.x = element_text(size = rel(1.3), angle = 0)) +
                                          theme(axis.text=element_text(size=12)) 

setwd("C:/Users/samjg/Documents/Github_repositories/Cvirginica_multistressor/RAnalysis")
pdf("Output/Survival/Survival_age_4days.pdf", width=4, height=6)
print(Age4_Survival_Boxplot)
dev.off()

```


### Age 8 days ALL DATA  ------------

```{r, SURVIVAL Age 8 days - all data}
age_8<- Av_length.survival_dat%>%
  filter(Day=="8") %>% 
  arrange(Survival) %>% 
  mutate(Survival = ifelse(Survival == last(Survival), 0.75, Survival)) # ID #12 was 0.86 -  whereas survival on day 4 was 0.75 - this is an artifact of increased numbers? I changed to 0.75 to reflect no losses between days 4 and 8


# Age 8 Length mod - all data -------------------------------------------------------------------------------------- #


Age8_Survival_lme_mod <- lme(Survival~OA*Salinity*Temp,random=~1|random_fact,data=age_8)
pander(anova(Age8_Survival_lme_mod), style='rmarkdown') # anova table of lm
# |        &nbsp;        | numDF | denDF | F-value |  p-value  |
# |:--------------------:|:-----:|:-----:|:-------:|:---------:|
# |   **(Intercept)**    |   1   |  16   |  46.08  | 4.355e-06 |
# |        **OA**        |   1   |  16   | 0.3291  |  0.5742   |
# |     **Salinity**     |   1   |  16   |  14.26  | 0.001652  | *
# |       **Temp**       |   1   |  16   |  0.028  |  0.8692   |
# |   **OA:Salinity**    |   1   |  16   |  0.112  |  0.7422   |
# |     **OA:Temp**      |   1   |  16   | 0.06913 |   0.796   |
# |  **Salinity:Temp**   |   1   |  16   | 0.1651  |  0.6899   |
# | **OA:Salinity:Temp** |   1   |  16   | 0.4805  |  0.4981   |
leveneTest(residuals(Age8_Survival_lme_mod) ~ age_8$Temp*age_8$OA*age_8$Salinity) # 0.41 pass
boxplot(residuals(Age8_Survival_lme_mod) ~ age_8$Temp*age_8$OA*age_8$Salinity) # visual of residuals grouped
qqnorm(resid(Age8_Survival_lme_mod)) # check for normality of residuals - looks okay


# run mod (lm model) 
Age8_Survival_lm_mod <- lm(Survival~OA*Salinity*Temp,data=age_8)
pander(anova(Age8_Survival_lm_mod), style='rmarkdown') # anova table of lm
# |        &nbsp;        | Df |  Sum Sq   |  Mean Sq  | F value |  Pr(>F)  |
# |:--------------------:|:--:|:---------:|:---------:|:-------:|:--------:|
# |        **OA**        | 1  |  0.0096   |  0.0096   | 0.3291  |  0.5742  |
# |     **Salinity**     | 1  |  0.4161   |  0.4161   |  14.26  | 0.001652 | *
# |       **Temp**       | 1  | 0.0008167 | 0.0008167 |  0.028  |  0.8692  |
# |   **OA:Salinity**    | 1  | 0.003267  | 0.003267  |  0.112  |  0.7422  |
# |     **OA:Temp**      | 1  | 0.002017  | 0.002017  | 0.06913 |  0.796   |
# |  **Salinity:Temp**   | 1  | 0.004817  | 0.004817  | 0.1651  |  0.6899  |
# | **OA:Salinity:Temp** | 1  |  0.01402  |  0.01402  | 0.4805  |  0.4981  |
# |    **Residuals**     | 16 |  0.4667   |  0.02917  |   NA    |    NA    |
library(stats)
shapiro.test(residuals(Age8_Survival_lm_mod)) # 0.1911 pass
leveneTest(residuals(Age8_Survival_lm_mod) ~ age_8$Temp*age_8$OA*age_8$Salinity) # 0.41 pass
boxplot(residuals(Age8_Survival_lm_mod) ~ age_8$Temp*age_8$OA*age_8$Salinity) # visual of residuals grouped
qqnorm(resid(Age8_Survival_lm_mod)) # check for normality of residuals - looks okay





# post hoc tests --------------------------------------------------------------------------------------------------- #

posthoc<-emmeans(Age8_Survival_lm_mod, pairwise~Salinity, adjust="tukey")

multcomp::cld(posthoc$emmeans,alpha = 0.5, Letters = letters)
 # Salinity emmean     SE df lower.CL upper.CL .group
 # Low       0.105 0.0493 16  0.00048    0.210  a    
 # High      0.368 0.0493 16  0.26381    0.473   b  
#71.4% higher under high salinity

# plot the data  ----------------------------------------------------------------------------------------------------- #
Age8_Survival_Boxplot_2 <- age_8 %>% 
  dplyr::group_by(OA,Salinity, Temp) %>% 
  dplyr::summarise(mean_surv = mean(Survival), 
                   n         = n(),
                   sd_surv   = sd(Survival),
                   se_surv   = sd_surv/(sqrt(n))) %>% 
                              ggplot(aes(x=fct_relevel(OA, c("Low", "High")), 
                                                             y=mean_surv, 
                                                             colour=fct_relevel(Salinity, c("Low", "High")), 
                                                             linetype = Temp)) +
                              geom_point(aes (fill = fct_relevel(Salinity, c("Low", "High")), shape = Temp), position = "dodge2") +
                              geom_errorbar(aes(ymin = mean_surv - se_surv, ymax = mean_surv + se_surv), width = 0.5, position= "dodge2") +
                              theme_classic() +  
                              #ylim(0,0.75) +
                              theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank())+ 
                              theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))+
                              labs(title="Age = 8 days", x ="pCO2 level", y = "Survival")+ 
                              theme(axis.title.y = element_text(size = rel(1.3), angle =90), axis.title.x = element_text(size = rel(1.3), angle = 0))+
                              theme(axis.text=element_text(size=12)) 

setwd("C:/Users/samjg/Documents/Github_repositories/Cvirginica_multistressor/RAnalysis")
pdf("Output/Survival/Survival_age_8days_MeanSE.pdf", width=8, height=6)
print(Age8_Survival_Boxplot_2)
dev.off()




##Here Low Salinity treatments are in Blue
Age8_Survival_Boxplot <-ggplot(data=age_8, aes(x=fct_relevel(OA, c("Low", "High")), 
                                        y=Survival, 
                                        colour=fct_relevel(Salinity, c("Low", "High")), 
                                        linetype = Temp)) +
                                          geom_boxplot() + 
                                          theme_classic() +  
                                          geom_jitter(position = position_dodge2(width = 0.75))+
                                          ylim(0,0.75) +
                                          stat_summary(fun.y="mean",position = position_dodge2(width = 0.75)) +
                                          theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank())+ 
                                          theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))+
                                          labs(title="Age = 24 hours (all data)", 
                                               x ="pCO2 level", 
                                               y = expression(Respiration~rate~"("~ng~L^{-1}~O[2]%.%indiv^{-1}%.% hr^{-1}~")")) + 
                                          theme(axis.title.y = element_text(size = rel(1.3), angle =90), 
                                                axis.title.x = element_text(size = rel(1.3), angle = 0)) +
                                          theme(axis.text=element_text(size=12)) 

setwd("C:/Users/samjg/Documents/Github_repositories/Cvirginica_multistressor/RAnalysis")
pdf("Output/Survival/Survival_age_8days.pdf", width=8, height=6)
print(Age8_Survival_Boxplot)
dev.off()

```


### Age 8 days HIGH TEMP ONLY ------------

```{r, SURVIVAL Age 8 days - HIGH TEMP ONLY}
age_8_hightemp <- Av_length.survival_dat %>%
                      filter(Day=="8") %>% 
                      dplyr::filter(Temp %in% 'High')


# Age 1 Length mod - all data -------------------------------------------------------------------------------------- #


Age8_Survival_lme_mod_hightemp <- lme(Survival~OA*Salinity,random=~1|random_fact,data=age_8_hightemp)
pander(anova(Age8_Survival_lme_mod_hightemp), style='rmarkdown') # anova table of lmer
# |     &nbsp;      | numDF | denDF | F-value |  p-value  |
# |:---------------:|:-----:|:-----:|:-------:|:---------:|
# | **(Intercept)** |   1   |   8   |  57.6   | 6.366e-05 |
# |     **OA**      |   1   |   8   | 0.1269  |  0.7309   |
# |  **Salinity**   |   1   |   8   |  14.93  | 0.004786  |
# | **OA:Salinity** |   1   |   8   |  1.388  |  0.2726   |
leveneTest(residuals(Age8_Survival_lme_mod_hightemp) ~ age_8_hightemp$OA*age_8_hightemp$Salinity) # 0.7127- pass
boxplot(residuals(Age8_Survival_lm_mod_hightemp) ~ age_8_hightemp$OA*age_8_hightemp$Salinity) # visual of residuals grouped
qqnorm(resid(Age8_Survival_lm_mod_hightemp)) # check for normality of residuals - looks okay






# run modle (lm)
Age8_Survival_lm_mod_hightemp <- lm(Survival~OA*Salinity,data=age_8_hightemp)
pander(anova(Age8_Survival_lm_mod_hightemp), style='rmarkdown') # anova table of lmer
#      &nbsp;      | Df |  Sum Sq  | Mean Sq  | F value |  Pr(>F)  |
# |:---------------:|:--:|:--------:|:--------:|:-------:|:--------:|
# |     **OA**      | 1  | 0.001408 | 0.001408 | 0.1269  |  0.7309  |
# |  **Salinity**   | 1  |  0.1657  |  0.1657  |  14.93  | 0.004786 |
# | **OA:Salinity** | 1  | 0.01541  | 0.01541  |  1.388  |  0.2726  |
# |  **Residuals**  | 8  |  0.0888  |  0.0111  |   NA    |    NA    |
shapiro.test(residuals(Age8_Survival_lm_mod_hightemp)) # 0.8541
leveneTest(residuals(Age8_Survival_lm_mod_hightemp) ~ age_8_hightemp$OA*age_8_hightemp$Salinity) # 0.7127- pass
boxplot(residuals(Age8_Survival_lm_mod_hightemp) ~ age_1_hightemp$OA*age_1_hightemp$Salinity) # visual of residuals grouped
qqnorm(resid(Age8_Survival_lm_mod_hightemp)) # check for normality of residuals - looks okay


# post hoc tests --------------------------------------------------------------------------------------------------- #

posthoc<-lsmeans(Age8_Survival_lme_mod_hightemp, ~Salinity, adjust="tukey")
posthoc<-emmeans(Age8_Survival_lme_mod_hightemp, pairwise~Salinity, adjust="tukey")

multcomp::cld(posthoc$emmeans,alpha = 0.5, Letters = letters)
# Salinity emmean     SE df lower.CL upper.CL .group
#  Low      0.0683 0.0635  6  -0.0871    0.224  a    
#  High     0.3483 0.0449  6   0.2384    0.458   b   



# plot the data  ----------------------------------------------------------------------------------------------------- #



Age8_Survival_Boxplot <- age_8_hightemp %>% 
  dplyr::group_by(OA,Salinity) %>% 
  dplyr::summarise(mean_surv = mean(Survival), 
                   n         = n(),
                   sd_surv   = sd(Survival),
                   se_surv   = sd_surv/(sqrt(n))) %>% 
                              ggplot(aes(x=fct_relevel(OA, c("Low", "High")), 
                                                             y=mean_surv, 
                                                             colour=fct_relevel(Salinity, c("Low", "High"))))+
                              geom_point(aes (fill = fct_relevel(Salinity, c("Low", "High"))), position = "dodge2") +
                              geom_errorbar(aes(ymin = mean_surv - se_surv, 
                                                ymax = mean_surv + se_surv,
                                                fill = fct_relevel(Salinity, c("Low", "High"))), 
                                                width = 0.5, position= "dodge2") +
                              theme_classic() +  
                              #ylim(0.2,0.6) +
                              theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank())+ 
                              theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))+
                              labs(title="Age = 8 days (high temp only)", x ="pCO2 level", y = "Survival")+ 
                              theme(axis.title.y = element_text(size = rel(1.3), 
                                                                angle =90), 
                                                                axis.title.x = element_text(size = rel(1.3), 
                                                                angle = 0)) +
                              theme(axis.text=element_text(size=12)) 

setwd("C:/Users/samjg/Documents/Github_repositories/Cvirginica_multistressor/RAnalysis")
pdf("Output/Survival/Survival_age_24hrs_MeanSE_hightemp.pdf", width=8, height=6)
print(Age8_Survival_Boxplot)
dev.off()



Age8_Survival_Boxplot <-ggplot(data=age_8_hightemp, aes(x=fct_relevel(OA, c("Low", "High")), 
                                        y=Survival, 
                                        colour=fct_relevel(Salinity, c("Low", "High")), 
                                        linetype = Temp)) +
                                          geom_boxplot() + 
                                          theme_classic() +  
                                          geom_jitter(position = position_dodge2(width = 0.75))+
                                         # ylim(0.2,0.6) +
                                          stat_summary(fun.y="mean",position = position_dodge2(width = 0.75)) +
                                          theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank())+ 
                                          theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))+
                                          labs(title="Age = 8 days (high temp only)", 
                                               x ="pCO2 level", 
                                               y = expression(Respiration~rate~"("~ng~L^{-1}~O[2]%.%indiv^{-1}%.% hr^{-1}~")")) + 
                                          theme(axis.title.y = element_text(size = rel(1.3), angle =90), 
                                                axis.title.x = element_text(size = rel(1.3), angle = 0)) +
                                          theme(axis.text=element_text(size=12)) 

setwd("C:/Users/samjg/Documents/Github_repositories/Cvirginica_multistressor/RAnalysis")
pdf("Output/Survival/Survival_age_8days_hightemp.pdf", width=8, height=6)
print(Age8_Survival_Boxplot)
dev.off()


```


### Age 11 days ALL DATA  ------------

```{r, SURVIVAL Age 11 days - all data}
age_11<- Av_length.survival_dat%>%
  filter(Day=="11") %>% 
  arrange(Survival) %>% 
  mutate(Survival = ifelse(Survival == last(Survival), 0.75, Survival)) # ID #12 was 0.116 -  whereas survival on day 11 was 0.75 - this is an artifact of increased numbers? I changed to 0.75 to reflect no losses between days 11 and 11


# Age 11 Length mod - all data -------------------------------------------------------------------------------------- #


Age11_Survival_lme_mod <- lme(Survival~OA*Salinity*Temp,random=~1|random_fact,data=age_11)
pander(anova(Age11_Survival_lme_mod), style='rmarkdown') # anova table of lm
# |        &nbsp;        | numDF | denDF | F-value |  p-value  |
# |:--------------------:|:-----:|:-----:|:-------:|:---------:|
# |   **(Intercept)**    |   1   |  16   |  29.69  | 5.353e-05 |
# |        **OA**        |   1   |  16   |  1.068  |  0.3167   |
# |     **Salinity**     |   1   |  16   |  9.248  | 0.007782  |
# |       **Temp**       |   1   |  16   |  1.072  |   0.316   |
# |   **OA:Salinity**    |   1   |  16   | 0.07552 |   0.787   |
# |     **OA:Temp**      |   1   |  16   | 0.3669  |  0.5532   |
# |  **Salinity:Temp**   |   1   |  16   |  0.386  |  0.5431   |
# | **OA:Salinity:Temp** |   1   |  16   | 0.6535  |  0.4307   |
# | **OA:Salinity:Temp** |   1   |  16   | 0.2301  |   0.638   |
leveneTest(residuals(Age11_Survival_lme_mod) ~ age_11$Temp*age_11$OA*age_11$Salinity) # 0.2159 pass
boxplot(residuals(Age11_Survival_lme_mod) ~ age_11$Temp*age_11$OA*age_11$Salinity) # visual of residuals grouped
qqnorm(resid(Age11_Survival_lme_mod)) # check for normality of residuals - looks okay


# run mod (lm model) 
Age11_Survival_lm_mod <- lm(Survival~OA*Salinity*Temp,data=age_11)
pander(anova(Age11_Survival_lm_mod), style='rmarkdown') # anova table of lm
# |        &nbsp;        | Df |  Sum Sq  | Mean Sq  | F value |  Pr(>F)  |
# |:--------------------:|:--:|:--------:|:--------:|:-------:|:--------:|
# |        **OA**        | 1  | 0.02429  | 0.02429  |  1.068  |  0.3167  |
# |     **Salinity**     | 1  |  0.2103  |  0.2103  |  9.248  | 0.007782 |
# |       **Temp**       | 1  | 0.02436  | 0.02436  |  1.072  |  0.316   |
# |   **OA:Salinity**    | 1  | 0.001717 | 0.001717 | 0.07552 |  0.787   |
# |     **OA:Temp**      | 1  | 0.008341 | 0.008341 | 0.3669  |  0.5532  |
# |  **Salinity:Temp**   | 1  | 0.008777 | 0.008777 |  0.386  |  0.5431  |
# | **OA:Salinity:Temp** | 1  | 0.01486  | 0.01486  | 0.6535  |  0.4307  |
# |    **Residuals**     | 16 |  0.3638  | 0.02274  |   NA    |    NA    |
library(stats)
shapiro.test(residuals(Age11_Survival_lm_mod)) # 0.008833 pass
leveneTest(residuals(Age11_Survival_lm_mod) ~ age_11$Temp*age_11$OA*age_11$Salinity) # 0.2159 pass
boxplot(residuals(Age11_Survival_lm_mod) ~ age_11$Temp*age_11$OA*age_11$Salinity) # visual of residuals grouped
qqnorm(resid(Age11_Survival_lm_mod)) # check for normality of residuals - looks okay





# post hoc tests --------------------------------------------------------------------------------------------------- #

posthoc<-emmeans(Age11_Survival_lm_mod, pairwise~Salinity, adjust="tukey")

multcomp::cld(posthoc$emmeans,alpha = 0.5, Letters = letters)
# Salinity emmean     SE df lower.CL upper.CL .group
#  Low      0.0741 0.0435 16  -0.0182    0.166  a    
#  High     0.2613 0.0435 16   0.1690    0.354   b   
#72% higher under high salinity

# plot the data  ----------------------------------------------------------------------------------------------------- #
Age11_Survival_Boxplot_2 <- age_11 %>% 
  dplyr::group_by(OA,Salinity, Temp) %>% 
  dplyr::summarise(mean_surv = mean(Survival), 
                   n         = n(),
                   sd_surv   = sd(Survival),
                   se_surv   = sd_surv/(sqrt(n))) %>% 
                              ggplot(aes(x=fct_relevel(OA, c("Low", "High")), 
                                                             y=mean_surv, 
                                                             colour=fct_relevel(Salinity, c("Low", "High")), 
                                                             linetype = Temp)) +
                              geom_point(aes (fill = fct_relevel(Salinity, c("Low", "High")), shape = Temp), position = "dodge2") +
                              geom_errorbar(aes(ymin = mean_surv - se_surv, ymax = mean_surv + se_surv), width = 0.5, position= "dodge2") +
                              theme_classic() +  
                              #ylim(0,0.75) +
                              theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank())+ 
                              theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))+
                              labs(title="Age = 11 days", x ="pCO2 level", y = "Survival")+ 
                              theme(axis.title.y = element_text(size = rel(1.3), angle =90), axis.title.x = element_text(size = rel(1.3), angle = 0))+
                              theme(axis.text=element_text(size=12)) 

setwd("C:/Users/samjg/Documents/Github_repositories/Cvirginica_multistressor/RAnalysis")
pdf("Output/Survival/Survival_age_11days_MeanSE.pdf", width=11, height=6)
print(Age11_Survival_Boxplot_2)
dev.off()




##Here Low Salinity treatments are in Blue
Age11_Survival_Boxplot <-ggplot(data=age_11, aes(x=fct_relevel(OA, c("Low", "High")), 
                                        y=Survival, 
                                        colour=fct_relevel(Salinity, c("Low", "High")), 
                                        linetype = Temp)) +
                                          geom_boxplot() + 
                                          theme_classic() +  
                                          geom_jitter(position = position_dodge2(width = 0.75))+
                                          ylim(0,0.75) +
                                          stat_summary(fun.y="mean",position = position_dodge2(width = 0.75)) +
                                          theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank())+ 
                                          theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))+
                                          labs(title="Age = 11 days (all data)", 
                                               x ="pCO2 level", 
                                               y = expression(Respiration~rate~"("~ng~L^{-1}~O[2]%.%indiv^{-1}%.% hr^{-1}~")")) + 
                                          theme(axis.title.y = element_text(size = rel(1.3), angle =90), 
                                                axis.title.x = element_text(size = rel(1.3), angle = 0)) +
                                          theme(axis.text=element_text(size=12)) 

setwd("C:/Users/samjg/Documents/Github_repositories/Cvirginica_multistressor/RAnalysis")
pdf("Output/Survival/Survival_age_11days.pdf", width=11, height=6)
print(Age11_Survival_Boxplot)
dev.off()

```


### Age 15 days ALL DATA  ------------

```{r, SURVIVAL Age 15 days - all data}
age_15<- Av_length.survival_dat%>%
  filter(Day=="15") %>% 
  arrange(Survival) %>% 
  mutate(Survival = ifelse(Survival == last(Survival), 0.75, Survival)) # ID #12 was 0.156 -  whereas survival on day 15 was 0.75 - this is an artifact of increased numbers? I changed to 0.75 to reflect no losses between days 15 and 15


# Age 15 Length mod - all data -------------------------------------------------------------------------------------- #


Age15_Survival_lme_mod <- lme(Survival~OA*Salinity*Temp,random=~1|random_fact,data=age_15)
pander(anova(Age15_Survival_lme_mod), style='rmarkdown') # anova table of lm
# |        &nbsp;        | numDF | denDF | F-value | p-value  |
# |:--------------------:|:-----:|:-----:|:-------:|:--------:|
# |   **(Intercept)**    |   1   |  16   |  13.17  | 0.002259 |
# |        **OA**        |   1   |  16   |  2.751  |  0.1166  |
# |     **Salinity**     |   1   |  16   |  6.994  | 0.01766  |
# |       **Temp**       |   1   |  16   | 0.4106  |  0.5307  |
# |   **OA:Salinity**    |   1   |  16   | 0.8238  |  0.3775  |
# |     **OA:Temp**      |   1   |  16   | 0.0958  |  0.7609  |
# |  **Salinity:Temp**   |   1   |  16   | 0.05448 |  0.8184  |
# | **OA:Salinity:Temp** |   1   |  16   | 0.5834  |  0.4561  |
leveneTest(residuals(Age15_Survival_lme_mod) ~ age_15$Temp*age_15$OA*age_15$Salinity) # 0.4224 pass
boxplot(residuals(Age15_Survival_lme_mod) ~ age_15$Temp*age_15$OA*age_15$Salinity) # visual of residuals grouped
qqnorm(resid(Age15_Survival_lme_mod)) # check for normality of residuals - looks okay


# run mod (lm model) 
Age15_Survival_lm_mod <- lm(Survival~OA*Salinity*Temp,data=age_15)
pander(anova(Age15_Survival_lm_mod), style='rmarkdown') # anova table of lm
# |        &nbsp;        | Df |  Sum Sq  | Mean Sq  | F value | Pr(>F)  |
# |:--------------------:|:--:|:--------:|:--------:|:-------:|:-------:|
# |        **OA**        | 1  | 0.06469  | 0.06469  |  2.751  | 0.1166  |
# |     **Salinity**     | 1  |  0.1644  |  0.1644  |  6.994  | 0.01766 |
# |       **Temp**       | 1  | 0.009654 | 0.009654 | 0.4106  | 0.5307  |
# |   **OA:Salinity**    | 1  | 0.01937  | 0.01937  | 0.8238  | 0.3775  |
# |     **OA:Temp**      | 1  | 0.002252 | 0.002252 | 0.0958  | 0.7609  |
# |  **Salinity:Temp**   | 1  | 0.001281 | 0.001281 | 0.05448 | 0.8184  |
# | **OA:Salinity:Temp** | 1  | 0.01372  | 0.01372  | 0.5834  | 0.4561  |
# |    **Residuals**     | 16 |  0.3762  | 0.02351  |   NA    |   NA    |
library(stats)
shapiro.test(residuals(Age15_Survival_lm_mod)) # 6.513e-05 pass
leveneTest(residuals(Age15_Survival_lm_mod) ~ age_15$Temp*age_15$OA*age_15$Salinity) # 0.4224 pass
boxplot(residuals(Age15_Survival_lm_mod) ~ age_15$Temp*age_15$OA*age_15$Salinity) # visual of residuals grouped
qqnorm(resid(Age15_Survival_lm_mod)) # check for normality of residuals - looks okay





# post hoc tests --------------------------------------------------------------------------------------------------- #

posthoc<-emmeans(Age15_Survival_lm_mod, pairwise~Salinity, adjust="tukey")

multcomp::cld(posthoc$emmeans,alpha = 0.5, Letters = letters)

 # Salinity emmean     SE df lower.CL upper.CL .group
 # Low      0.0308 0.0443 16   -0.063    0.125  a    
 # High     0.1963 0.0443 16    0.103    0.290   b  
#36.1% higher under high salinity

# plot the data  ----------------------------------------------------------------------------------------------------- #
Age15_Survival_Boxplot_2 <- age_15 %>% 
  dplyr::group_by(OA,Salinity, Temp) %>% 
  dplyr::summarise(mean_surv = mean(Survival), 
                   n         = n(),
                   sd_surv   = sd(Survival),
                   se_surv   = sd_surv/(sqrt(n))) %>% 
                              ggplot(aes(x=fct_relevel(OA, c("Low", "High")), 
                                                             y=mean_surv, 
                                                             colour=fct_relevel(Salinity, c("Low", "High")), 
                                                             linetype = Temp)) +
                              geom_point(aes (fill = fct_relevel(Salinity, c("Low", "High")), shape = Temp), position = "dodge2") +
                              geom_errorbar(aes(ymin = mean_surv - se_surv, ymax = mean_surv + se_surv), width = 0.5, position= "dodge2") +
                              theme_classic() +  
                              #ylim(0,0.75) +
                              theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank())+ 
                              theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))+
                              labs(title="Age = 15 days", x ="pCO2 level", y = "Survival")+ 
                              theme(axis.title.y = element_text(size = rel(1.3), angle =90), axis.title.x = element_text(size = rel(1.3), angle = 0))+
                              theme(axis.text=element_text(size=12)) 

setwd("C:/Users/samjg/Documents/Github_repositories/Cvirginica_multistressor/RAnalysis")
pdf("Output/Survival/Survival_age_15days_MeanSE.pdf", width=15, height=6)
print(Age15_Survival_Boxplot_2)
dev.off()




##Here Low Salinity treatments are in Blue
Age15_Survival_Boxplot <-ggplot(data=age_15, aes(x=fct_relevel(OA, c("Low", "High")), 
                                        y=Survival, 
                                        colour=fct_relevel(Salinity, c("Low", "High")), 
                                        linetype = Temp)) +
                                          geom_boxplot() + 
                                          theme_classic() +  
                                          geom_jitter(position = position_dodge2(width = 0.75))+
                                          ylim(0,0.75) +
                                          stat_summary(fun.y="mean",position = position_dodge2(width = 0.75)) +
                                          theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank())+ 
                                          theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))+
                                          labs(title="Age = 15 days (all data)", 
                                               x ="pCO2 level", 
                                               y = expression(Respiration~rate~"("~ng~L^{-1}~O[2]%.%indiv^{-1}%.% hr^{-1}~")")) + 
                                          theme(axis.title.y = element_text(size = rel(1.3), angle =90), 
                                                axis.title.x = element_text(size = rel(1.3), angle = 0)) +
                                          theme(axis.text=element_text(size=12)) 

setwd("C:/Users/samjg/Documents/Github_repositories/Cvirginica_multistressor/RAnalysis")
pdf("Output/Survival/Survival_age_15days.pdf", width=15, height=6)
print(Age15_Survival_Boxplot)
dev.off()

```
